# Generated by Django 6.0.1 on 2026-02-11 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0013_order_payment_status_setup_alter_setup_setup_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NCMBulkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('from_branch', models.CharField(default='TINKUNE', max_length=100)),
                ('delivery_type', models.CharField(default='Door2Door', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncm_bulk_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NCM Bulk Log',
                'verbose_name_plural': 'NCM Bulk Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NCMBulkLogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('batch_started', 'Batch Started'), ('order_sent', 'Order Sent'), ('order_failed', 'Order Failed'), ('order_skipped', 'Order Skipped'), ('batch_completed', 'Batch Completed'), ('status_synced', 'Status Synced'), ('error', 'Error')], max_length=30)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ncm.ncmbulklog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NCMBulkLogOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('shipping_address', models.CharField(blank=True, max_length=500)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('destination_branch', models.CharField(blank=True, max_length=100)),
                ('ncm_order_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=20)),
                ('ncm_status', models.CharField(blank=True, default='Pickup Order Created', max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ncm.ncmbulklog')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncm_bulk_log_entries', to='dashboard.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
