# Generated by Django 5.2 on 2026-08-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncm', '0003_ncmbulklog_cancel_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncmbulklog',
            name='send_options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
