# Generated by Django 5.2 on 2026-06-19 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this connection', max_length=255)),
                ('spreadsheet_id', models.CharField(help_text='Google Sheet ID (from the URL)', max_length=500)),
                ('spreadsheet_url', models.URLField(blank=True, help_text='Full Google Sheet URL', max_length=1000)),
                ('sheet_name', models.CharField(default='Sheet1', help_text='Tab/sheet name', max_length=255)),
                ('sync_model', models.CharField(choices=[('orders', 'Orders'), ('products', 'Products'), ('customers', 'Customers'), ('custom', 'Custom / Any Sheet')], default='orders', max_length=50)),
                ('field_mapping', models.JSONField(blank=True, default=dict, help_text='Mapping: {"A": "order_number", "B": "customer_name", ...}')),
                ('header_row', models.PositiveIntegerField(default=1, help_text='Row number containing headers')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_sync_enabled', models.BooleanField(default=False, help_text='Enable periodic auto-sync')),
                ('auto_sync_interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_direction', models.CharField(blank=True, choices=[('to_sheet', 'To Sheet'), ('from_sheet', 'From Sheet'), ('both', 'Both')], max_length=20)),
                ('last_sync_status', models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('', 'Never synced')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Sheet Connection',
                'verbose_name_plural': 'Google Sheet Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('to_sheet', 'Django → Sheet'), ('from_sheet', 'Sheet → Django'), ('both', 'Two-Way Merge')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=20)),
                ('rows_synced', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='google_sheets.googlesheetconnection')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-synced_at'],
            },
        ),
    ]
