# Generated by Django 5.2 on 2026-06-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlesheetconnection',
            name='spreadsheet_id',
        ),
        migrations.AddField(
            model_name='googlesheetconnection',
            name='apps_script_url',
            field=models.URLField(blank=True, help_text='Apps Script Web App URL', max_length=2000),
        ),
        migrations.AddField(
            model_name='googlesheetconnection',
            name='connection_type',
            field=models.CharField(choices=[('csv', 'Published CSV URL (Read Only)'), ('apps_script', 'Apps Script Web App (Two-Way Sync)')], default='csv', max_length=20),
        ),
        migrations.AddField(
            model_name='googlesheetconnection',
            name='csv_url',
            field=models.URLField(blank=True, help_text='Published CSV URL', max_length=2000),
        ),
        migrations.AlterField(
            model_name='googlesheetconnection',
            name='spreadsheet_url',
            field=models.URLField(blank=True, help_text='Link to view the sheet', max_length=1000),
        ),
    ]
