# Generated by Django 5.2 on 2026-05-24 09:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0054_add_metadata_to_orderactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_currency_unit', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Reward points earned per 1 unit of currency spent', max_digits=8)),
                ('min_bill_total_for_reward', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Minimum bill total required to earn rewards', max_digits=12)),
                ('max_points_per_bill', models.PositiveIntegerField(default=5000, help_text='Maximum points earnable from a single bill')),
                ('points_expiry_days', models.PositiveIntegerField(default=365, help_text='Days until points expire (0 = never)')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reward Configuration',
                'verbose_name_plural': 'Reward Configuration',
            },
        ),
        migrations.CreateModel(
            name='BillUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='bill_uploads/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash for duplicate detection', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending OCR'), ('processing', 'Processing'), ('completed', 'Completed'), ('review', 'Needs Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'OCR Failed')], db_index=True, default='pending', max_length=20)),
                ('ocr_provider', models.CharField(blank=True, choices=[('aws_textract', 'AWS Textract'), ('google_docai', 'Google Document AI'), ('manual', 'Manual Entry')], max_length=30)),
                ('ocr_confidence', models.FloatField(blank=True, help_text='Overall OCR confidence 0-100', null=True)),
                ('raw_ocr_json', models.JSONField(blank=True, default=dict)),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_uploads', to='dashboard.customer')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='bill_rewards.billupload')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bills', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill Upload',
                'verbose_name_plural': 'Bill Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRewardBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.IntegerField(default=0)),
                ('total_redeemed', models.IntegerField(default=0)),
                ('total_expired', models.IntegerField(default=0)),
                ('current_balance', models.IntegerField(default=0)),
                ('last_earned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_balance', to='dashboard.customer')),
            ],
            options={
                'verbose_name': 'Customer Reward Balance',
                'verbose_name_plural': 'Customer Reward Balances',
            },
        ),
        migrations.CreateModel(
            name='ExtractedBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('shop_name', models.CharField(blank=True, max_length=255)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confidence_customer_name', models.FloatField(blank=True, null=True)),
                ('confidence_shop_name', models.FloatField(blank=True, null=True)),
                ('confidence_invoice_number', models.FloatField(blank=True, null=True)),
                ('confidence_bill_date', models.FloatField(blank=True, null=True)),
                ('confidence_subtotal', models.FloatField(blank=True, null=True)),
                ('confidence_tax', models.FloatField(blank=True, null=True)),
                ('confidence_total', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted', to='bill_rewards.billupload')),
            ],
            options={
                'verbose_name': 'Extracted Bill',
                'verbose_name_plural': 'Extracted Bills',
            },
        ),
        migrations.CreateModel(
            name='ExtractedLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_description', models.CharField(blank=True, max_length=500)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('line_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('match_confidence', models.FloatField(blank=True, help_text='Product match confidence 0-100', null=True)),
                ('match_method', models.CharField(blank=True, help_text='exact, alias, fuzzy, category_predict', max_length=30)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='bill_rewards.extractedbill')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_line_items', to='dashboard.product')),
                ('predicted_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_bill_items', to='dashboard.category')),
            ],
            options={
                'verbose_name': 'Extracted Line Item',
                'verbose_name_plural': 'Extracted Line Items',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='dashboard.product')),
            ],
            options={
                'verbose_name': 'Product Alias',
                'verbose_name_plural': 'Product Aliases',
                'ordering': ['alias_name'],
            },
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('adjusted', 'Admin Adjustment')], max_length=20)),
                ('points', models.IntegerField(help_text='Positive for earn, negative for redeem/expire')),
                ('balance_after', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_transactions', to='bill_rewards.billupload')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to='dashboard.customer')),
            ],
            options={
                'verbose_name': 'Reward Transaction',
                'verbose_name_plural': 'Reward Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillProductTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(help_text='First day of the week/month period')),
                ('period_type', models.CharField(choices=[('week', 'Weekly'), ('month', 'Monthly')], max_length=10)),
                ('total_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bill_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_trends', to='dashboard.product')),
            ],
            options={
                'verbose_name': 'Bill Product Trend',
                'verbose_name_plural': 'Bill Product Trends',
                'ordering': ['-period_date'],
                'unique_together': {('product', 'period_date', 'period_type')},
            },
        ),
        migrations.AddIndex(
            model_name='billupload',
            index=models.Index(fields=['status', '-created_at'], name='bill_reward_status_e0d273_idx'),
        ),
        migrations.AddIndex(
            model_name='billupload',
            index=models.Index(fields=['file_hash'], name='bill_reward_file_ha_4b5320_idx'),
        ),
    ]
