# Generated by Django 6.0.1 on 2026-01-28 07:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_adjust_stock',
            field=models.BooleanField(default=False, verbose_name='Adjust Stock Levels'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_cancel_orders',
            field=models.BooleanField(default=False, verbose_name='Cancel Orders'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_create_customers',
            field=models.BooleanField(default=True, verbose_name='Create Customers'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_create_orders',
            field=models.BooleanField(default=True, verbose_name='Create Orders'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_create_products',
            field=models.BooleanField(default=False, verbose_name='Create Products'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete_customers',
            field=models.BooleanField(default=False, verbose_name='Delete Customers'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete_orders',
            field=models.BooleanField(default=False, verbose_name='Delete Orders'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete_products',
            field=models.BooleanField(default=False, verbose_name='Delete Products'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_customers',
            field=models.BooleanField(default=True, verbose_name='Edit Customers'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_orders',
            field=models.BooleanField(default=True, verbose_name='Edit Orders'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_prices',
            field=models.BooleanField(default=False, verbose_name='Edit Prices'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_products',
            field=models.BooleanField(default=False, verbose_name='Edit Products'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_export_data',
            field=models.BooleanField(default=False, verbose_name='Export Data (Excel/CSV)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_give_discounts',
            field=models.BooleanField(default=True, verbose_name='Give Discounts'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_dispatch',
            field=models.BooleanField(default=False, verbose_name='Manage Dispatch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_inventory',
            field=models.BooleanField(default=False, verbose_name='Manage Inventory'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_scan_barcodes',
            field=models.BooleanField(default=False, verbose_name='Use Barcode Scanner'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_cost_price',
            field=models.BooleanField(default=False, verbose_name='View Cost Prices'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_customers',
            field=models.BooleanField(default=True, verbose_name='View Customers'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_dispatch',
            field=models.BooleanField(default=False, verbose_name='View Dispatch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_financial_reports',
            field=models.BooleanField(default=False, verbose_name='View Financial Reports'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_inventory',
            field=models.BooleanField(default=True, verbose_name='View Inventory'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_orders',
            field=models.BooleanField(default=True, verbose_name='View Orders'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_products',
            field=models.BooleanField(default=True, verbose_name='View Products'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_reports',
            field=models.BooleanField(default=False, verbose_name='View Reports'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_sales_reports',
            field=models.BooleanField(default=False, verbose_name='View Sales Reports'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum discount percentage allowed (0-100)', max_digits=5, verbose_name='Maximum Discount %'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
