# Generated by Django 6.0.1 on 2026-01-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_approve_returns',
            field=models.BooleanField(default=False, verbose_name='Can Approve/Reject Returns'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_create_returns',
            field=models.BooleanField(default=False, verbose_name='Can Create Returns'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete_returns',
            field=models.BooleanField(default=False, verbose_name='Can Delete Returns'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_returns',
            field=models.BooleanField(default=False, verbose_name='Can Edit Returns'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_process_refunds',
            field=models.BooleanField(default=False, verbose_name='Can Process Refunds'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_returns',
            field=models.BooleanField(default=False, verbose_name='Can View Returns'),
        ),
    ]
