# Generated by Django 6.0.1 on 2026-02-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_can_approve_returns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vendor_id',
            field=models.CharField(blank=True, help_text='Unique vendor ID for logistics providers like NCM', max_length=100, null=True, unique=True),
        ),
    ]
