# Generated by Django 6.0.1 on 2026-02-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_delete_dispatch',
            field=models.BooleanField(default=False),
        ),
    ]
