# Generated by Django 6.0.1 on 2026-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_can_delete_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_delete_targets',
            field=models.BooleanField(default=False, verbose_name='Can Delete Targets'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_targets',
            field=models.BooleanField(default=False, verbose_name='Can Edit Targets'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_set_targets',
            field=models.BooleanField(default=False, verbose_name='Can Set Targets'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_own_targets',
            field=models.BooleanField(default=True, verbose_name='Can View Own Targets'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_targets',
            field=models.BooleanField(default=False, verbose_name='Can View All Targets'),
        ),
    ]
