# Generated by Django 6.0.1 on 2026-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_can_delete_targets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_create_purchases',
            field=models.BooleanField(default=False, verbose_name='Can Create Purchases'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_make_supplier_payments',
            field=models.BooleanField(default=False, verbose_name='Can Make Supplier Payments'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_suppliers',
            field=models.BooleanField(default=False, verbose_name='Can Manage Suppliers'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_purchases',
            field=models.BooleanField(default=False, verbose_name='Can View Purchases'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_staff_performance',
            field=models.BooleanField(default=False, verbose_name='Can View Staff Performance'),
        ),
    ]
