# Generated by Django 6.0.1 on 2026-02-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_can_create_purchases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_add_cities',
            field=models.BooleanField(default=False, verbose_name='Can Add Cities'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete_cities',
            field=models.BooleanField(default=False, verbose_name='Can Delete Cities'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_cities',
            field=models.BooleanField(default=False, verbose_name='Can Edit Cities'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_cities',
            field=models.BooleanField(default=False, verbose_name='Can View Cities'),
        ),
    ]
