# Generated by Django 6.0.1 on 2026-02-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_can_add_cities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_daily_sales_reports',
            field=models.BooleanField(default=False, verbose_name='Can View Daily Sales Reports'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_product_sales_reports',
            field=models.BooleanField(default=False, verbose_name='Can View Product Sales Reports'),
        ),
    ]
