# Generated by Django 6.0.1 on 2026-02-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_can_view_daily_sales_reports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='can_edit_orders',
            field=models.BooleanField(default=False),
        ),
    ]
