# Generated by Django 6.0.1 on 2026-02-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_set_edit_orders_default_false'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name used in code (e.g. administrator, sales, warehouse)', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name shown in UI', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted without extra confirmation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['display_name'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='sales', max_length=50),
        ),
    ]
