# Generated by Django 6.0.1 on 2026-02-25 07:33

from django.db import migrations


def create_initial_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    roles = [
        {
            'name': 'administrator',
            'display_name': 'Administrator',
            'description': 'Full access to all system features and settings',
            'is_system': True,
        },
        {
            'name': 'warehouse',
            'display_name': 'Warehouse',
            'description': 'Manage inventory, dispatch, and warehouse operations',
            'is_system': True,
        },
        {
            'name': 'sales',
            'display_name': 'Sales',
            'description': 'Manage orders, customers, and sales operations',
            'is_system': True,
        },
    ]
    for role_data in roles:
        Role.objects.get_or_create(name=role_data['name'], defaults=role_data)


def reverse_initial_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.filter(name__in=['administrator', 'warehouse', 'sales']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_role_model'),
    ]

    operations = [
        migrations.RunPython(create_initial_roles, reverse_initial_roles),
    ]
