# Generated by Django 6.0.1 on 2026-02-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_populate_initial_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_total_revenue',
            field=models.BooleanField(default=False, verbose_name='Can View Total Revenue'),
        ),
    ]
