# Generated by Django 6.0.1 on 2026-02-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_can_view_total_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_dashboard',
            field=models.BooleanField(default=True, verbose_name='Can View Dashboard'),
        ),
    ]
