# Generated by Django 6.0.1 on 2026-02-25 12:18

from django.db import migrations


def set_dashboard_permission(apps, schema_editor):
    """Set can_view_dashboard=True for all existing users"""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.all().update(can_view_dashboard=True)


def reverse_set_dashboard_permission(apps, schema_editor):
    """Reverse: set can_view_dashboard=False for all users"""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.all().update(can_view_dashboard=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_can_view_dashboard'),
    ]

    operations = [
        migrations.RunPython(set_dashboard_permission, reverse_set_dashboard_permission),
    ]
