# Generated by Django 6.0.1 on 2026-02-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_set_default_dashboard_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_create_ncm_orders',
            field=models.BooleanField(default=False, verbose_name='Can Create NCM Orders'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete_ncm_orders',
            field=models.BooleanField(default=False, verbose_name='Can Delete NCM Orders'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_ncm_orders',
            field=models.BooleanField(default=False, verbose_name='Can Edit NCM Orders'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_ncm_branches',
            field=models.BooleanField(default=False, verbose_name='Can Manage NCM Branches'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_ncm_bulk_logs',
            field=models.BooleanField(default=False, verbose_name='Can Manage NCM Bulk Logs'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_sync_ncm_orders',
            field=models.BooleanField(default=False, verbose_name='Can Sync NCM Orders'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_ncm_branches',
            field=models.BooleanField(default=False, verbose_name='Can View NCM Branches'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_ncm_bulk_logs',
            field=models.BooleanField(default=False, verbose_name='Can View NCM Bulk Logs'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_ncm_orders',
            field=models.BooleanField(default=False, verbose_name='Can View NCM Orders'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_ncm_trash',
            field=models.BooleanField(default=False, verbose_name='Can View NCM Trash'),
        ),
    ]
