# Generated by Django 6.0.1 on 2026-02-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customuser_can_create_ncm_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_inventory_cost',
            field=models.BooleanField(default=False, verbose_name='Can View Inventory Cost'),
        ),
    ]
