# Generated by Django 6.0.1 on 2026-03-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customuser_can_view_inventory_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_on_hold_orders',
            field=models.BooleanField(default=False),
        ),
    ]
