# Generated by Django 6.0.1 on 2026-03-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_customuser_can_view_on_hold_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_product_value',
            field=models.BooleanField(default=False, verbose_name='View Product Value'),
        ),
    ]
