# Generated by Django 6.0.1 on 2026-03-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_customuser_can_view_product_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='can_view_product_value',
            new_name='can_toggle_product_price',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='can_toggle_product_price',
            field=models.BooleanField(default=False, verbose_name='Toggle Product Price'),
        ),
    ]
