# Generated by Django 6.0.1 on 2026-03-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_can_view_product_value_to_can_toggle_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_export_orders',
            field=models.BooleanField(default=False, verbose_name='Can Export Orders to Excel'),
        ),
    ]
