# Generated by Django 6.0.1 on 2026-03-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_can_export_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_orders_list',
            field=models.BooleanField(default=False, verbose_name='Can View All Orders List'),
        ),
    ]
