# Generated by Django 6.0.1 on 2026-03-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_customuser_can_view_orders_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_cost_unit_price',
            field=models.BooleanField(default=False, verbose_name='View Cost Unit Price'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_selling_unit_price',
            field=models.BooleanField(default=False, verbose_name='View Selling Unit Price'),
        ),
    ]
