# Generated by Django 6.0.1 on 2026-03-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_selling_cost_unit_price_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_toggle_stock_valuation',
            field=models.BooleanField(default=False, verbose_name='Toggle Stock Valuation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_valuation_cost',
            field=models.BooleanField(default=False, verbose_name='Valuation by Cost Price'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_valuation_selling',
            field=models.BooleanField(default=False, verbose_name='Valuation by Selling Price'),
        ),
    ]
