# Generated by Django 6.0.1 on 2026-03-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_stock_valuation_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_hrm',
            field=models.BooleanField(default=False, verbose_name='Can View HRM'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_hrm_asset_management',
            field=models.BooleanField(default=False, verbose_name='Can View Asset Management'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_hrm_attendance',
            field=models.BooleanField(default=False, verbose_name='Can View Attendance'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_hrm_hr_management',
            field=models.BooleanField(default=False, verbose_name='Can View HR Management'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_hrm_payroll',
            field=models.BooleanField(default=False, verbose_name='Can View Payroll Management'),
        ),
    ]
