# Generated by Django 6.0.1 on 2026-04-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_customuser_can_view_hrm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_access_todo',
            field=models.BooleanField(default=False, verbose_name='Access to Todo/Ticketing'),
        ),
    ]
