# Generated by Django 6.0.1 on 2026-04-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_customuser_can_access_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_low_stock_alerts',
            field=models.BooleanField(default=False, verbose_name='Can View Low Stock Alerts'),
        ),
    ]
