# Generated by Django 5.2 on 2026-06-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_fix_phone_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_access_offer_price',
            field=models.BooleanField(default=False, verbose_name='Can Access Offer Price'),
        ),
    ]
