# Generated by Django 5.2 on 2026-06-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_customuser_can_access_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_access_follow_ups',
            field=models.BooleanField(default=False, verbose_name='Can Access Follow Ups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_setup_follow_up_status',
            field=models.BooleanField(default=False, verbose_name='Can Setup Follow Up Status'),
        ),
    ]
