# Generated by Django 5.2 on 2026-06-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_customuser_can_access_follow_ups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='default_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
