# Generated by Django 5.2 on 2026-06-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_role_default_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_content_management',
            field=models.BooleanField(default=False, verbose_name='Can View Content Management'),
        ),
    ]
