# Generated by Django 5.2 on 2026-07-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_customuser_can_view_content_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='can_view_dashboard',
            field=models.BooleanField(default=False, verbose_name='Dashboard Access'),
        ),
    ]
