# Generated by Django 5.2 on 2026-07-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_can_view_dashboard_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_follow_up_report',
            field=models.BooleanField(default=False, verbose_name='Can View Follow Up Report'),
        ),
    ]
