# Generated by Django 5.2 on 2026-07-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_add_can_view_follow_up_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_hrm_incomplete_attendance',
            field=models.BooleanField(default=False, verbose_name='Incomplete Attendance Alert'),
        ),
    ]
