# Generated by Django 5.2 on 2026-07-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_customuser_can_view_hrm_incomplete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_dashboard_incomplete_attendance',
            field=models.BooleanField(default=False, verbose_name='Incomplete Attendance Alert'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_dashboard_orders_by_source',
            field=models.BooleanField(default=False, verbose_name='Orders by Source'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_dashboard_orders_overview',
            field=models.BooleanField(default=False, verbose_name='Orders Overview'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_dashboard_sales_overview',
            field=models.BooleanField(default=False, verbose_name='Sales Overview'),
        ),
    ]
