# Generated by Django 5.2 on 2026-07-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_customuser_can_view_dashboard_incomplete_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_fix_hrm_incomplete_attendance',
            field=models.BooleanField(default=False, verbose_name='Fix Incomplete Attendance'),
        ),
    ]
