# Generated by Django 5.2 on 2026-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_customuser_can_fix_hrm_incomplete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_orders_by_source_report',
            field=models.BooleanField(default=False, verbose_name='Can View Orders by Source Report'),
        ),
    ]
