# Generated by Django 5.2 on 2026-07-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_customuser_can_view_orders_by_source_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_create_resources',
            field=models.BooleanField(default=False, verbose_name='Can Create/Edit/Delete Resources'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_resources',
            field=models.BooleanField(default=False, verbose_name='Can View Resources'),
        ),
    ]
