# Generated by Django 5.2 on 2026-08-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_customuser_can_create_resources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_configure_audit',
            field=models.BooleanField(default=False, verbose_name='Can Configure Audit Settings'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_export_audit_logs',
            field=models.BooleanField(default=False, verbose_name='Can Export Audit Logs'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_sessions',
            field=models.BooleanField(default=False, verbose_name='Can Revoke Sessions & Resolve Alerts'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_all_users_activity',
            field=models.BooleanField(default=False, verbose_name="Can View Everyone's Activity"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_audit_trail',
            field=models.BooleanField(default=False, verbose_name='Can Access Sentinel Vault'),
        ),
    ]
