# Generated by Django 5.2 on 2026-08-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_customuser_can_configure_audit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_rtv_report',
            field=models.BooleanField(default=False, verbose_name='Can View RTV Report'),
        ),
    ]
