# Generated by Django 5.2 on 2026-08-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_customuser_can_view_rtv_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_export_follow_ups',
            field=models.BooleanField(default=False, verbose_name='Can Export Follow Ups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_export_logistics_bulk_logs',
            field=models.BooleanField(default=False, verbose_name='Can Export Logistics Bulk Logs'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_export_logistics_orders',
            field=models.BooleanField(default=False, verbose_name='Can Export Logistics Orders'),
        ),
    ]
