# Generated by Django 5.2 on 2026-09-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_customuser_id_alter_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_customer_reports',
            field=models.BooleanField(default=False, verbose_name='Can View Customer Advanced Report'),
        ),
    ]
