# Generated by Django 5.2 on 2026-09-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_customuser_can_view_customer_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_dashboard_hourly_sales',
            field=models.BooleanField(default=False, verbose_name='Hourly Sales Breakdown'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_dashboard_top_products',
            field=models.BooleanField(default=False, verbose_name='Top Products Sold'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_dashboard_warehouse_info',
            field=models.BooleanField(default=False, verbose_name='Warehouse Info'),
        ),
    ]
