# Generated by Django 6.0.1 on 2026-04-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_add_selected_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='WooCommerceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_order_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', models.CharField(blank=True, max_length=30)),
                ('billing_data', models.JSONField(blank=True, default=dict)),
                ('shipping_data', models.JSONField(blank=True, default=dict)),
                ('line_items_json', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('sync_source', models.CharField(default='woocommerce_plugin', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='woo_link', to='store.order')),
            ],
            options={
                'verbose_name': 'WooCommerce Order',
                'verbose_name_plural': 'WooCommerce Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
