# Generated by Django 5.2 on 2026-09-02 09:25

from django.db import migrations, models


def backfill_woo_date_created(apps, schema_editor):
    """Recover each order's real placement time from the payload we already
    stored, so a store that was backfilled before this field existed doesn't
    show every order dated to the moment of the sync.

    Walks the table in primary-key windows rather than with .iterator(): under
    MySQLdb an unbuffered streaming cursor can't have writes interleaved on the
    same connection, and bulk_update mid-stream drops it with OperationalError
    (2006).
    """
    from integrations.services import parse_woo_datetime

    WooCommerceOrder = apps.get_model('integrations', 'WooCommerceOrder')
    chunk_size = 500
    last_pk = 0

    while True:
        rows = list(
            WooCommerceOrder.objects
            .filter(pk__gt=last_pk, woo_date_created__isnull=True)
            .order_by('pk')
            .values_list('pk', 'raw_payload')[:chunk_size]
        )
        if not rows:
            break
        last_pk = rows[-1][0]

        updates = []
        for pk, raw_payload in rows:
            placed_at = parse_woo_datetime(raw_payload or {})
            if placed_at is not None:
                updates.append(WooCommerceOrder(pk=pk, woo_date_created=placed_at))
        if updates:
            WooCommerceOrder.objects.bulk_update(updates, ['woo_date_created'])


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woocommerceorder',
            options={'ordering': ['-woo_date_created', '-created_at'], 'verbose_name': 'WooCommerce Order', 'verbose_name_plural': 'WooCommerce Orders'},
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='woo_date_created',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_woo_date_created, migrations.RunPython.noop),
    ]
