# Generated by Django 6.0.1 on 2026-04-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_category_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
