# Generated by Django 6.0.1 on 2026-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('confirmed', 'Confirm Order'), ('inquiry', 'Inquiry Only')], default='confirmed', max_length=20),
        ),
    ]
