# Generated by Django 6.0.1 on 2026-04-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_variant',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_variant',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
