# Generated by Django 5.2 on 2026-04-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_add_selected_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='backordered_qty',
            field=models.IntegerField(default=0, help_text='Units waiting on new stock'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reserved_qty',
            field=models.IntegerField(default=0, help_text='Units filled from real stock'),
        ),
    ]
