# Generated by Django 5.2 on 2026-08-30 12:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_storecustomer_cart_customer_order_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_valley_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Delivery fee for the Kathmandu Valley districts listed below.', max_digits=10)),
                ('default_charge', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Fee used for any district that has no rule of its own.', max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('500'), help_text='Orders at or above this subtotal ship free. 0 disables it.', max_digits=10)),
                ('valley_districts', models.CharField(default='KATHMANDU, LALITPUR, BHAKTAPUR', help_text='Comma-separated districts treated as inside the valley.', max_length=255)),
                ('default_delivery_time', models.CharField(blank=True, default='Delivered within 3-5 days', help_text='Shown on the order form when a rule has no time of its own.', max_length=140)),
                ('default_delivery_time_np', models.CharField(blank=True, default='', help_text='Nepali version of the line above (optional).', max_length=180)),
                ('show_covered_areas', models.BooleanField(default=True, help_text="Show the branch's covered areas on the order form.")),
                ('show_delivery_time', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery setting',
                'verbose_name_plural': 'Delivery settings',
            },
        ),
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(db_index=True, max_length=80)),
                ('branch_code', models.CharField(blank=True, default='', help_text='Blank = the rule covers every branch in the district.', max_length=40)),
                ('branch_name', models.CharField(blank=True, default='', max_length=140)),
                ('charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('free_above', models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal at or above which this rule ships free. Blank = use the site default.', max_digits=10, null=True)),
                ('delivery_time', models.CharField(blank=True, default='', help_text="e.g. 'Delivered within 3-4 days'.", max_length=140)),
                ('delivery_time_np', models.CharField(blank=True, default='', help_text="e.g. '३-४ दिन भित्र डेलिभरी हुनेछ'.", max_length=180)),
                ('covered_areas', models.TextField(blank=True, default='', help_text="Comma-separated areas. Blank = fall back to the courier's own list.")),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery charge',
                'verbose_name_plural': 'Delivery charges',
                'ordering': ['district', 'branch_name', 'branch_code'],
                'indexes': [models.Index(fields=['district', 'branch_code'], name='store_deliv_distric_674164_idx')],
                'unique_together': {('district', 'branch_code')},
            },
        ),
    ]
