# Generated by Django 5.2 on 2026-09-01 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_setup_sort_order'),
        ('store', '0011_alter_cartitem_unique_together_cartitem_variation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackInStockNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_in_stock_notices', to='store.storecustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_in_stock_notices', to='dashboard.product')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_in_stock_notices', to='dashboard.productvariation')),
            ],
            options={
                'verbose_name': 'back-in-stock notice',
                'verbose_name_plural': 'back-in-stock notices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'notified_at'], name='store_backi_product_f7a01b_idx'), models.Index(fields=['variation', 'notified_at'], name='store_backi_variati_4d2e98_idx')],
            },
        ),
    ]
