# Generated by Django 5.2 on 2026-09-01 10:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_setup_sort_order'),
        ('store', '0012_alter_deliverycharge_free_above_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycharge',
            name='free_above',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal at or above which this rule ships free. Blank = this district is always charged.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliverysetting',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('500'), help_text='Orders at or above this subtotal ship free, in districts that have no rule of their own. 0 disables it.', max_digits=10),
        ),
        migrations.CreateModel(
            name='BulkDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text="Internal name, e.g. 'Beard oil — festival bundle'.", max_length=140)),
                ('scope', models.CharField(choices=[('variation', 'One variation'), ('product', 'One product'), ('category', 'A whole category'), ('all', 'Every product')], default='product', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='When two rules target the same thing, the higher number wins.')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Blank = live immediately.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Blank = never expires.', null=True)),
                ('show_on_cards', models.BooleanField(default=True, help_text='Show the offer on listing/home product cards (simple products).')),
                ('badge_text', models.CharField(blank=True, default='', help_text="Overrides the automatic 'Save 10%' line. Blank = generated.", max_length=60)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_discounts', to='dashboard.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_discounts', to='dashboard.product')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_discounts', to='dashboard.productvariation')),
            ],
            options={
                'verbose_name': 'bulk discount',
                'verbose_name_plural': 'bulk discounts',
                'ordering': ['-priority', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkDiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.PositiveIntegerField(default=2, help_text='Units the shopper must take for this rung to apply.', validators=[django.core.validators.MinValueValidator(1)])),
                ('discount_type', models.CharField(choices=[('percent', '% off each'), ('amount', 'Rs. off each'), ('price', 'Fixed price each')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('label', models.CharField(blank=True, default='', help_text="Optional name for this rung, e.g. 'Family pack'.", max_length=60)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='store.bulkdiscount')),
            ],
            options={
                'verbose_name': 'bulk discount tier',
                'verbose_name_plural': 'bulk discount tiers',
                'ordering': ['min_qty'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkdiscount',
            index=models.Index(fields=['scope', 'is_active'], name='store_bulkd_scope_cc1b52_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkdiscount',
            index=models.Index(fields=['product', 'is_active'], name='store_bulkd_product_534be5_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkdiscount',
            index=models.Index(fields=['variation', 'is_active'], name='store_bulkd_variati_2eb34f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bulkdiscounttier',
            unique_together={('rule', 'min_qty')},
        ),
    ]
