# Generated by Django 5.2 on 2026-09-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_alter_invoicetemplate_currency_symbol'),
        ('store', '0013_alter_deliverycharge_free_above_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('theme1', 'Theme 1 - Classic (current design)'), ('theme2', 'Theme 2 - Conversion landing page')], default='theme1', help_text='Which design every product page uses unless the product overrides it.', max_length=10)),
                ('highlights', models.TextField(blank=True, default='', help_text='PRODUCT HIGHLIGHTS bullets - one per line.')),
                ('pay_chips', models.CharField(blank=True, default='', help_text='Payment chips, comma separated (e.g. Prepaid, COD).', max_length=300)),
                ('pay_bullets', models.TextField(blank=True, default='', help_text='PAYMENT & OFFERS bullets - one per line.')),
                ('return_label', models.CharField(blank=True, default='', max_length=80)),
                ('return_value', models.CharField(blank=True, default='', max_length=160)),
                ('warranty_label', models.CharField(blank=True, default='', max_length=80)),
                ('warranty_value', models.CharField(blank=True, default='', max_length=160)),
                ('shipping_label', models.CharField(blank=True, default='', max_length=80)),
                ('shipping_value', models.CharField(blank=True, default='', max_length=160)),
                ('trust_json', models.TextField(blank=True, default='', help_text='Trust row, as JSON: [{"icon": "delivery", "text": "..."}]. Icons: delivery, payment, secure, return, warranty.')),
                ('buy_label', models.CharField(blank=True, default='', max_length=60)),
                ('info_title', models.CharField(blank=True, default='', max_length=80)),
                ('video_title', models.CharField(blank=True, default='', max_length=80)),
                ('videos', models.TextField(blank=True, default='', help_text='One clip per line: video | poster | creator. Self-hosted files only - a YouTube/Vimeo embed cannot take the custom play, mute and expand controls.')),
                ('stat_text', models.TextField(blank=True, default='', help_text='Trust stat. First line is the big figure, the rest is the supporting copy.')),
                ('stat_image', models.CharField(blank=True, default='', max_length=300)),
                ('benefit_text', models.CharField(blank=True, default='', max_length=300)),
                ('benefit_image', models.CharField(blank=True, default='', max_length=300)),
                ('steps_title', models.CharField(blank=True, default='', max_length=80)),
                ('steps', models.TextField(blank=True, default='', help_text='One step per line: title | instruction | image. Numbers are generated from the line order - do not type them.')),
                ('ingredients_title', models.CharField(blank=True, default='', max_length=80)),
                ('ingredients', models.TextField(blank=True, default='', help_text='One per line: name | image | short note.')),
                ('buy_action', models.CharField(choices=[('modal', 'Open the one-step COD checkout'), ('checkout', 'Add to cart and go to the checkout page')], default='modal', max_length=10)),
                ('ship_fee', models.CharField(blank=True, default='', help_text='Flat delivery fee for Theme 2 orders. Leave blank to use Setup > Delivery Charge Setup, which prices by district.', max_length=40)),
                ('checkout_title', models.CharField(blank=True, default='', max_length=80)),
                ('place_label', models.CharField(blank=True, default='', max_length=60)),
                ('cod_label', models.CharField(blank=True, default='', max_length=80)),
                ('phone_prefix', models.CharField(blank=True, default='', max_length=10)),
                ('phone_hint', models.CharField(blank=True, default='', max_length=160)),
                ('footer_address', models.CharField(blank=True, default='', max_length=300)),
                ('footer_phone', models.CharField(blank=True, default='', max_length=120)),
                ('footer_credit', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product page theme',
                'verbose_name_plural': 'product page theme',
            },
        ),
        migrations.CreateModel(
            name='ProductThemeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(blank=True, choices=[('', 'Use the global setting'), ('theme1', 'Theme 1 - Classic (current design)'), ('theme2', 'Theme 2 - Conversion landing page')], default='', help_text='Blank inherits the global product-page design.', max_length=10)),
                ('highlights', models.TextField(blank=True, default='')),
                ('pay_chips', models.CharField(blank=True, default='', max_length=300)),
                ('pay_bullets', models.TextField(blank=True, default='')),
                ('return_value', models.CharField(blank=True, default='', max_length=160)),
                ('warranty_value', models.CharField(blank=True, default='', max_length=160)),
                ('shipping_value', models.CharField(blank=True, default='', max_length=160)),
                ('videos', models.TextField(blank=True, default='')),
                ('stat_text', models.TextField(blank=True, default='')),
                ('stat_image', models.CharField(blank=True, default='', max_length=300)),
                ('benefit_text', models.CharField(blank=True, default='', max_length=300)),
                ('benefit_image', models.CharField(blank=True, default='', max_length=300)),
                ('steps', models.TextField(blank=True, default='')),
                ('ingredients', models.TextField(blank=True, default='')),
                ('ship_fee', models.CharField(blank=True, default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_theme', to='dashboard.product')),
            ],
            options={
                'verbose_name': 'product page override',
                'verbose_name_plural': 'product page overrides',
            },
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('voter_key', models.CharField(db_index=True, max_length=48)),
                ('value', models.CharField(choices=[('up', 'Helpful'), ('down', 'Not helpful')], default='up', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to='store.storecustomer')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='store.productreview')),
            ],
            options={
                'unique_together': {('review', 'voter_key')},
            },
        ),
    ]
