# Generated by Django 5.2 on 2026-09-03 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productpagetheme_productthemeoverride_reviewvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_theme/%Y/%m/')),
                ('kind', models.CharField(choices=[('image', 'Photo'), ('video', 'Video')], default='image', max_length=6)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product page media',
                'verbose_name_plural': 'product page media',
                'ordering': ['-created_at'],
            },
        ),
    ]
