# Generated by Django 5.2 on 2026-09-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_thememedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpagetheme',
            name='before_after',
            field=models.TextField(blank=True, default='', help_text='One pair per line: before image | after image | caption.'),
        ),
        migrations.AddField(
            model_name='productpagetheme',
            name='before_after_title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='productthemeoverride',
            name='before_after',
            field=models.TextField(blank=True, default=''),
        ),
    ]
