# Generated by Django 5.2 on 2026-09-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productpagetheme_before_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpagetheme',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Features or manual. One per line: title | description.'),
        ),
        migrations.AddField(
            model_name='productpagetheme',
            name='features_title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='productpagetheme',
            name='info_media',
            field=models.TextField(blank=True, default='', help_text='Description gallery. One block per line: image | heading | description. Any cell may be left out.'),
        ),
        migrations.AddField(
            model_name='productthemeoverride',
            name='before_after_title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='productthemeoverride',
            name='buy_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='productthemeoverride',
            name='features',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productthemeoverride',
            name='features_title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='productthemeoverride',
            name='info_media',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productthemeoverride',
            name='info_title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='productthemeoverride',
            name='ingredients_title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='productthemeoverride',
            name='steps_title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='productthemeoverride',
            name='video_title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
