# Generated by Django 5.2 on 2026-09-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_productpagetheme_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_now', models.CharField(blank=True, default='', max_length=80)),
                ('add_to_cart', models.CharField(blank=True, default='', max_length=80)),
                ('sold_out', models.CharField(blank=True, default='', max_length=80)),
                ('save_for_later', models.CharField(blank=True, default='', max_length=80)),
                ('saved', models.CharField(blank=True, default='', max_length=80)),
                ('form_title', models.CharField(blank=True, default='', max_length=120)),
                ('form_subtitle', models.CharField(blank=True, default='', max_length=160)),
                ('confirm_title', models.CharField(blank=True, default='', max_length=80)),
                ('confirm_sub', models.CharField(blank=True, default='', max_length=120)),
                ('inquiry_title', models.CharField(blank=True, default='', max_length=80)),
                ('inquiry_sub', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'store button label',
                'verbose_name_plural': 'store button labels',
            },
        ),
    ]
