# Generated by Django 5.2 on 2026-09-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_storelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelabel',
            name='choose_option',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
