# Generated by Django 5.2 on 2026-07-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcontact',
            name='meta_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
