# Generated by Django 5.2 on 2026-07-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0002_crmcontact_meta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmintegration',
            name='channel_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook Messenger'), ('tiktok', 'TikTok'), ('gmail', 'Gmail'), ('outlook', 'Outlook'), ('zoho_mail', 'Zoho Mail')], max_length=30),
        ),
    ]
