# Generated by Django 5.2 on 2026-07-07 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0003_alter_crmintegration_channel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmconversation',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='trendycrm.crmintegration'),
        ),
    ]
