# Generated by Django 5.2 on 2026-07-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0004_crmconversation_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=20),
        ),
    ]
