# Generated by Django 5.2 on 2026-07-08 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0005_crmmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
