# Generated by Django 5.2 on 2026-07-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0006_alter_crmmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
    ]
