# Generated by Django 5.2 on 2026-07-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0007_alter_crmmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmconversation',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
