# Generated by Django 5.2 on 2026-07-09 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0008_crmconversation_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmconversation',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
