# Generated by Django 5.2 on 2026-07-09 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0009_alter_crmconversation_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMSocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_post_id', models.CharField(max_length=255, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('picture_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='trendycrm.crmintegration')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CRMSocialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_comment_id', models.CharField(max_length=255, unique=True)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('workflow_status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=20)),
                ('visibility_status', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden'), ('spam', 'Spam')], default='visible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='trendycrm.crmsocialcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trendycrm.crmsocialpost')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
