# Generated by Django 5.2 on 2026-07-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0010_crmsocialpost_crmsocialcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmsocialpost',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
