# Generated by Django 5.2 on 2026-07-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0011_crmsocialpost_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmsocialpost',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
