# Generated by Django 5.2 on 2026-07-13 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0012_crmsocialpost_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Google Gemini API key (audio, simple FAQ via Flash)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='OpenAI API key for ChatGPT Premium (complex text, images)', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='CRMPageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, help_text='Main product name sold on this page', max_length=300, null=True)),
                ('price', models.CharField(blank=True, help_text='Product price (e.g. NPR 1,200)', max_length=100, null=True)),
                ('brand_tone', models.CharField(choices=[('friendly', 'Friendly & Casual'), ('professional', 'Professional & Formal'), ('energetic', 'Energetic & Hype'), ('empathetic', 'Empathetic & Supportive'), ('luxury', 'Luxury & Exclusive')], default='friendly', max_length=20)),
                ('checkout_link', models.URLField(blank=True, help_text='Direct checkout / buy link sent in DMs', max_length=1000, null=True)),
                ('custom_faq', models.TextField(blank=True, help_text='Custom FAQs or product description for the AI knowledge base', null=True)),
                ('comment_auto_reply_enabled', models.BooleanField(default=False, help_text='Auto-reply publicly to comments and DM the sender')),
                ('public_reply_template', models.TextField(blank=True, default='Just sent the link to your DMs! 💌', help_text='The public comment reply text (The Hook)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(help_text='The connected social channel this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='page_profile', to='trendycrm.crmintegration')),
            ],
            options={
                'verbose_name': 'Page Profile',
                'ordering': ['integration__channel_type'],
            },
        ),
    ]
