# Generated by Django 5.2 on 2026-07-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0013_crmchatbotconfig_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMCreditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('auto_reply', 'Auto Reply'), ('intent_classify', 'Intent Classification'), ('comment_dm', 'Comment-to-DM'), ('manual_test', 'Manual Test'), ('top_up', 'Top Up')], max_length=30)),
                ('credits_used', models.IntegerField(default=1)),
                ('model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Credit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='ai_model',
            field=models.CharField(choices=[('multi_auto', 'Multi-Model Auto (Recommended)'), ('gpt-4o', 'GPT-4o (Premium)'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (Fast)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Cheapest)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro')], default='multi_auto', max_length=50),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='faq_text',
            field=models.TextField(blank=True, help_text='Common FAQs and their answers.', null=True),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='offerings',
            field=models.TextField(blank=True, help_text='Products and services you sell.', null=True),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='playbook',
            field=models.TextField(blank=True, help_text='How to handle tricky situations, complaints, refunds.', null=True),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='response_tone',
            field=models.CharField(choices=[('professional_friendly', 'Professional & Friendly'), ('formal', 'Formal'), ('casual', 'Casual'), ('energetic', 'Energetic & Hype'), ('empathetic', 'Empathetic & Supportive')], default='professional_friendly', max_length=30),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='tone_voice',
            field=models.TextField(blank=True, help_text='How should the AI speak? Describe tone, style, brand voice.', null=True),
        ),
        migrations.AlterField(
            model_name='crmchatbotconfig',
            name='about_blurb',
            field=models.TextField(blank=True, help_text='About your business for the AI', null=True),
        ),
    ]
