# Generated by Django 5.2 on 2026-07-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0015_crmlabel_crmconversation_labels_crmnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmsocialcomment',
            name='reactions_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='crmsocialpost',
            name='reactions_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
