# Generated by Django 5.2 on 2026-07-14 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0016_crmsocialcomment_reactions_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this automation', max_length=200)),
                ('trigger_keyword', models.CharField(blank=True, help_text='Keyword to match (leave blank if match_type=any)', max_length=200)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains Keyword'), ('any', 'Any Comment')], default='contains', max_length=20)),
                ('public_reply', models.TextField(help_text='The public comment reply text shown on the post')),
                ('send_dm', models.BooleanField(default=False, help_text='Also send a private DM to the commenter')),
                ('dm_message', models.TextField(blank=True, help_text='The private DM body (can include links, product details, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_count', models.IntegerField(default=0, help_text='How many times this automation has fired')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(help_text='The social page this automation applies to', on_delete=django.db.models.deletion.CASCADE, related_name='comment_automations', to='trendycrm.crmintegration')),
            ],
            options={
                'verbose_name': 'Comment Automation',
                'verbose_name_plural': 'Comment Automations',
                'ordering': ['-created_at'],
            },
        ),
    ]
