# Generated by Django 5.2 on 2026-07-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0017_comment_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmconversation',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
