# Generated by Django 5.2 on 2026-07-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0018_crmconversation_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmsocialpost',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
