# Generated by Django 5.2 on 2026-07-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0019_crmsocialpost_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='creativity_level',
            field=models.CharField(choices=[('0.3', 'Strict & Factual'), ('0.7', 'Balanced'), ('1.2', 'Creative & Marketing')], default='0.7', max_length=10),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='human_handoff',
            field=models.CharField(choices=[('never', 'Never'), ('issues', 'On Issues/Refunds'), ('complex', 'On Complex Questions'), ('always', 'Always')], default='issues', max_length=20),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='primary_language',
            field=models.CharField(choices=[('auto', 'Auto-Detect'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ne', 'Nepali'), ('hi', 'Hindi')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='response_length',
            field=models.CharField(choices=[('100', 'Short & Punchy'), ('500', 'Standard'), ('1500', 'Detailed & Explanatory')], default='500', max_length=10),
        ),
    ]
