# Generated by Django 5.2 on 2026-07-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0020_crmchatbotconfig_creativity_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmchatbotconfig',
            name='human_handoff',
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='handoff_triggers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
