# Generated by Django 5.2 on 2026-07-17 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0021_remove_crmchatbotconfig_human_handoff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmintegration',
            name='chatbot_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations', to='trendycrm.crmchatbotconfig'),
        ),
    ]
