# Generated by Django 5.2 on 2026-07-17 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0022_crmintegration_chatbot_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcreditlog',
            name='chatbot_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_logs', to='trendycrm.crmchatbotconfig'),
        ),
    ]
