# Generated by Django 5.2 on 2026-07-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0024_crmchatbotconfig_provider_routing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmchatbotconfig',
            name='ai_model',
            field=models.CharField(choices=[('multi_auto', 'Multi-Model Auto (Recommended)'), ('gpt-4o', 'GPT-4o (Premium)'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (Fast)'), ('gemini-flash-latest', 'Gemini Flash (Cheapest)'), ('gemini-pro-latest', 'Gemini Pro')], default='multi_auto', max_length=50),
        ),
        migrations.AlterField(
            model_name='crmconversation',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('gmail', 'Gmail'), ('outlook', 'Outlook'), ('zoho_mail', 'Zoho Mail'), ('email', 'Email'), ('sms', 'SMS'), ('web', 'Web Chat')], default='web', max_length=20),
        ),
    ]
