# Generated by Django 5.2 on 2026-07-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0025_alter_crmchatbotconfig_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='crm_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='crmmessage',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='crmmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('audio', 'Audio'), ('document', 'Document')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='crmmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
