# Generated by Django 5.2 on 2026-07-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0026_crmmessage_attachment_crmmessage_attachment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='business_address',
            field=models.TextField(blank=True, help_text='Shop/office address the AI can give out', null=True),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='cities_served',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='social_instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='social_tiktok',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='social_whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
