# Generated by Django 5.2 on 2026-07-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0027_crmchatbotconfig_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmconversation',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crmconversation',
            name='last_human_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmmessage',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='crmmessage',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
    ]
