# Generated by Django 5.2 on 2026-08-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0028_crmconversation_ai_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
