# Generated by Django 5.2 on 2026-08-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0029_crmchatbotconfig_last_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmmessage',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crmmessage',
            name='system_level',
            field=models.CharField(blank=True, choices=[('info', 'Info'), ('warning', 'Warning')], default='', max_length=10),
        ),
    ]
