# Generated by Django 5.2 on 2026-08-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0030_crmmessage_is_system_crmmessage_system_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmmessage',
            name='ai_intent',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
