# Generated by Django 5.2 on 2026-08-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0031_crmmessage_ai_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmmessage',
            name='event_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='crmmessage',
            name='event_kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='crmmessage',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmmessage',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
