# Generated by Django 5.2 on 2026-08-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0033_backfill_ai_failure_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmmessage',
            name='client_token',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
