# Generated by Django 5.2 on 2026-08-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendycrm', '0034_crmmessage_client_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmchatbotconfig',
            name='triage_rules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
