# Generated by Django 5.2 on 2026-05-31 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_taskfollowup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskFollowUp',
        ),
    ]
