"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os 
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS must be explicitly set in production .env, e.g.:
#   ALLOWED_HOSTS=office.orajil.com.np,www.office.orajil.com.np
# Defaulting to '*' in development only; production MUST override this.
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="office.orajil.com.np,www.office.orajil.com.np,orajil.com.np,www.orajil.com.np,localhost,127.0.0.1", cast=Csv())

AUTH_USER_MODEL = 'accounts.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

EXTERNAL_APPS = [
     "dashboard",
    "accounts",
    "ncm",
    "pick_and_drop",
    "chat",
    "hrm",
    "todo",
    "store",
    "inventory",
    "rest_framework",
    "rest_framework.authtoken",
    "integrations",
    "bill_rewards",
    "google_sheets",
    "trendycrm",
    "resources",
]
INSTALLED_APPS.extend(EXTERNAL_APPS)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'myproject.middleware.GracefulSessionInterruptionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.company_setup',
                'dashboard.context_processors.low_stock_notifications',
                'chat.context_processors.unread_message_count',
                'store.context_processors.store_context',
                'dashboard.context_processors.maintenance_mode',
                'dashboard.context_processors.expiry_notifications',
                'dashboard.context_processors.incomplete_attendance_alert',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'
ASGI_APPLICATION = 'myproject.asgi.application'



# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        # ── Production robustness settings ──────────────────────────────
        # Reuse DB connections for 60 seconds instead of open/closing per request.
        # Prevents 'MySQL server has gone away' under high load.
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=60, cast=int),
        # CONN_HEALTH_CHECKS: ping the connection before reuse (Django 4.1+)
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {
            'charset': 'utf8mb4',
            # Abort if DB doesn't respond in 10 seconds (prevents worker hang → 500)
            'connect_timeout': 10,
            # Re-raise exceptions instead of swallowing them silently
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'  # Nepali Time (UTC+5:45)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# ========== SESSION CONFIGURATION ==========
# Session settings for 12-hour persistent login
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Store sessions in database
SESSION_COOKIE_AGE = 43200  # 12 hours in seconds
SESSION_COOKIE_HTTPONLY = True  # Prevent JS access for security
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)  # Set True in .env for production HTTPS
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)  # Set True in .env for production HTTPS

# For cPanel/Apache deployments where HTTPS is terminated by the proxy
# (Apache sits in front of Django). This lets Django detect HTTPS correctly.
# Only enable this if your cPanel uses Apache as a reverse proxy with SSL:
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Keep session even after browser closes
SESSION_SAVE_EVERY_REQUEST = True  # Reset expiry on every request (sliding window)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ======================== Cache Configuration ========================
# Using LocMemCache (per-process in-memory) which works without Redis.
# Each worker has its own cache — but 60-second TTL is short enough that
# stale data is acceptable. Swap BACKEND to Redis if you add Redis later:
#   BACKEND: 'django.core.cache.backends.redis.RedisCache'
#   LOCATION: 'redis://127.0.0.1:6379/1'
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'dashboard-ctx-cache',
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='ermilan30@gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = 'System Admin <ermilan30@gmail.com>'
# Password Reset Settings
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour
# uuqw cnwz ybnt wvut


# ======================== NCM API Configuration ========================
NCM_API_KEY = config('NCM_API_KEY')
NCM_API_BASE_URL = config('NCM_API_BASE_URL')
NCM_API_BASE_URL_V2 = config('NCM_API_BASE_URL_V2')

# ===================== Webhook Configuration =====================
# Webhook Security: Set this in your .env file
NCM_WEBHOOK_SECRET = config('NCM_WEBHOOK_SECRET', default=None)
WOOCOMMERCE_WEBHOOK_SECRET = config('WOOCOMMERCE_WEBHOOK_SECRET', default='')
SITE_URL = config('SITE_URL', default='https://office.orajil.com.np').rstrip('/')

META_PAGE_ACCESS_TOKEN = config('META_PAGE_ACCESS_TOKEN', default='')
FACEBOOK_APP_ID = config('FACEBOOK_APP_ID', default='')
FACEBOOK_APP_SECRET = config('FACEBOOK_APP_SECRET', default='')
INSTAGRAM_APP_ID = config('INSTAGRAM_APP_ID', default='')
INSTAGRAM_APP_SECRET = config('INSTAGRAM_APP_SECRET', default='')
TIKTOK_CLIENT_ID = config('TIKTOK_CLIENT_ID', default='')
TIKTOK_CLIENT_SECRET = config('TIKTOK_CLIENT_SECRET', default='')
FACEBOOK_WEBHOOK_VERIFY_TOKEN = config('FACEBOOK_WEBHOOK_VERIFY_TOKEN', default='')

# Kept for backward compatibility
FACEBOOK_CLIENT_ID = config('FACEBOOK_CLIENT_ID', default=FACEBOOK_APP_ID)
FACEBOOK_CLIENT_SECRET = config('FACEBOOK_CLIENT_SECRET', default=FACEBOOK_APP_SECRET)
FACEBOOK_CONFIG_ID = config('FACEBOOK_CONFIG_ID', default='')
# ===================== Pick and Drop API Configuration =====================
PND_API_KEY = config('PND_API_KEY', default='')
PND_API_SECRET = config('PND_API_SECRET', default='')
PND_API_BASE_URL = config('PND_API_BASE_URL', default='https://pickndropnepal.com')

# ===================== SMS Configuration =====================
# SMS Provider: 'console', 'twilio', 'sparrow', 'atuha'
SMS_PROVIDER = config('SMS_PROVIDER', default='console')
SMS_ENABLED = config('SMS_ENABLED', default=False, cast=bool)
SMS_API_KEY = config('SMS_API_KEY', default=None)
SMS_SENDER_ID = config('SMS_SENDER_ID', default='EcommerceAdmin')

# Twilio configuration (if using Twilio)
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default=None)
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default=None)
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default=None)

# ===================== Real-time Configuration =====================
# Auto-sync polling interval (seconds)
ORDER_AUTO_SYNC_INTERVAL = config('ORDER_AUTO_SYNC_INTERVAL', default=14400, cast=int)

# Check for pending updates every X minutes
WEBHOOK_PENDING_CHECK_INTERVAL = config('WEBHOOK_PENDING_CHECK_INTERVAL', default=30, cast=int)

# ======================== Logging Configuration ========================
# Ensure logs directory exists before configuring handlers
_LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(_LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module}.{funcName}:{lineno} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {asctime} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'INFO',
            'formatter': 'simple',
        },
        # ── NEW: Captures ALL Django 500 errors to a dedicated log ───────
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'level': 'ERROR',
            'filename': os.path.join(_LOG_DIR, 'django_errors.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'ncm_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'level': 'DEBUG',
            'filename': os.path.join(_LOG_DIR, 'ncm_integration.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'trendycrm_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'level': 'DEBUG',
            'filename': os.path.join(_LOG_DIR, 'trendycrm.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            # Customer messages routinely contain emoji and Devanagari.
            'encoding': 'utf-8',
        },
        'ncm_webhook_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'level': 'DEBUG',
            'filename': os.path.join(_LOG_DIR, 'ncm_webhooks.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'ncm_sms_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'level': 'DEBUG',
            'filename': os.path.join(_LOG_DIR, 'ncm_sms.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
        'adms_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'level': 'DEBUG',
            'filename': os.path.join(_LOG_DIR, 'adms.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'integrations_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'level': 'DEBUG',
            'filename': os.path.join(_LOG_DIR, 'integrations.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # ── NEW: Catch ALL unhandled 500 errors from Django core ─────────
        'django': {
            'handlers': ['console', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # ── NEW: Log every 500 request with full traceback ───────────────
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # ── NEW: Log DB errors (connection drops, timeouts) ──────────────
        'django.db.backends': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'ncm': {
            'handlers': ['console', 'ncm_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'webhook': {
            'handlers': ['console', 'ncm_webhook_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'sms': {
            'handlers': ['console', 'ncm_sms_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'hrm.adms': {
            'handlers': ['console', 'adms_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'integrations': {
            'handlers': ['console', 'integrations_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # CRM inbox, Meta sync and the AI auto-reply engine. Without this the
        # reason a reply was skipped ("staff replied recently", "out of credits",
        # "rate limited") was never written anywhere.
        'trendycrm': {
            'handlers': ['console', 'trendycrm_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# logs directory is already guaranteed to exist above (os.makedirs(_LOG_DIR, exist_ok=True))

# ===================== Bill OCR & Rewards Configuration =====================
# OCR Provider: 'auto', 'aws_textract', 'google_docai', or 'manual'
BILL_OCR_PROVIDER = config('BILL_OCR_PROVIDER', default='auto')
# Confidence threshold below which bills are flagged for admin review
BILL_OCR_REVIEW_THRESHOLD = config('BILL_OCR_REVIEW_THRESHOLD', default=70, cast=int)
# AWS credentials (if using Textract)
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_REGION = config('AWS_REGION', default='us-east-1')
# Google Document AI (if using)
GOOGLE_DOCAI_PROJECT = config('GOOGLE_DOCAI_PROJECT', default='')
GOOGLE_DOCAI_LOCATION = config('GOOGLE_DOCAI_LOCATION', default='us')
GOOGLE_DOCAI_PROCESSOR_ID = config('GOOGLE_DOCAI_PROCESSOR_ID', default='')
# OCR.space API Key (if using)
OCR_SPACE_API_KEY = config('OCR_SPACE_API_KEY', default='')

# ===================== Celery Configuration =====================
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Run synchronously for local dev unless redis is available and explicit
# Trigger reload
