# Generated by Django 6.0.1 on 2026-02-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                apps.get_model('logistics', 'LogisticsProvider').objects.get_or_create(
                    code='NCM',
                    defaults={
                        'name': 'NCM Logistics',
                        'api_url': 'https://api.ncmnepal.com',
                        'api_token': 'your_ncm_api_token',
                        'is_active': True
                    }
                )
            ),
            reverse_code=lambda apps, schema_editor: (
                apps.get_model('logistics', 'LogisticsProvider').objects.filter(code='NCM').delete()
            )
        ),
    ]
