# Generated by Django 5.2 on 2026-07-24 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='resource',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Rich text shown in the highlighted NOTES callout'),
        ),
        migrations.AddField(
            model_name='resource',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Short one-line summary shown collapsed', max_length=300),
        ),
        migrations.AddField(
            model_name='resource',
            name='version',
            field=models.CharField(blank=True, default='v1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Rich text body (HTML) — use numbered lists for steps'),
        ),
        migrations.CreateModel(
            name='ResourceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='fa-folder', max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_topics_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcetopic'),
        ),
        migrations.CreateModel(
            name='ResourceRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('resource', 'user')},
            },
        ),
    ]
