# Generated by Django 6.0.1 on 2026-03-19 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_awardtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gift', models.CharField(blank=True, default='', max_length=255)),
                ('monetary_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='award_certificates/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='award_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='hrm.awardtype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='hrm.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
