# Generated by Django 6.0.1 on 2026-03-20 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0009_resignation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_type', models.CharField(choices=[('involuntary', 'Involuntary'), ('voluntary', 'Voluntary'), ('retirement', 'Retirement'), ('contract_end', 'Contract End'), ('misconduct', 'Misconduct'), ('layoff', 'Layoff')], max_length=20)),
                ('termination_date', models.DateField()),
                ('notice_date', models.DateField()),
                ('notice_period', models.CharField(blank=True, default='', max_length=100)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('document', models.FileField(blank=True, null=True, upload_to='termination_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('revoked', 'Revoked')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='hrm.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
