# Generated by Django 6.0.1 on 2026-03-20 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_termination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('performance', 'Performance'), ('attendance', 'Attendance'), ('conduct', 'Conduct'), ('policy_violation', 'Policy Violation'), ('safety', 'Safety'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('verbal', 'Verbal'), ('written', 'Written'), ('final', 'Final')], default='verbal', max_length=10)),
                ('warning_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('improvement_plan', models.BooleanField(default=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='warning_documents/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='hrm.employee')),
                ('warning_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings_issued', to='hrm.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
