# Generated by Django 6.0.1 on 2026-03-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0011_warning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('harassment', 'Harassment'), ('discrimination', 'Discrimination'), ('workplace_conditions', 'Workplace Conditions'), ('management_issues', 'Management Issues'), ('policy_violation', 'Policy Violation'), ('safety', 'Safety'), ('other', 'Other')], max_length=25)),
                ('subject', models.CharField(max_length=255)),
                ('complaint_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('assigned_to', models.CharField(blank=True, default='', max_length=255)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='complaint_documents/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='submitted', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('against', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_against', to='hrm.employee')),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to='hrm.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
