# Generated by Django 6.0.1 on 2026-03-20 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0013_assettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('asset_code', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('under_maintenance', 'Under Maintenance'), ('retired', 'Retired'), ('disposed', 'Disposed')], default='available', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='new', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('supplier', models.CharField(blank=True, default='', max_length=255)),
                ('warranty_info', models.CharField(blank=True, default='', max_length=255)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='asset_images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='asset_documents/')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('sum_of_years', 'Sum of Years Digits'), ('units_of_production', 'Units of Production'), ('none', 'None')], default='none', max_length=25)),
                ('useful_life_years', models.PositiveIntegerField(default=5)),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='hrm.assettype')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='hrm.employee')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
