# Generated by Django 6.0.1 on 2026-03-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0015_attendancepolicy_shift_attendanceregularization'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='break_duration',
            field=models.PositiveIntegerField(default=60, help_text='Break duration in minutes'),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='grace_period',
            field=models.PositiveIntegerField(default=15, help_text='Grace period in minutes'),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_night_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='working_hours',
            field=models.DecimalField(decimal_places=1, default=8.0, max_digits=4),
        ),
    ]
