# Generated by Django 6.0.1 on 2026-03-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0016_shift_break_duration_shift_break_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='early_departure_grace',
            field=models.PositiveIntegerField(default=15, help_text='Minutes before shift end allowed to leave early'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Overtime rate per hour', max_digits=8),
        ),
    ]
