# Generated by Django 6.0.1 on 2026-03-26 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0018_attendance_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceregularization',
            name='attendance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularizations', to='hrm.attendancerecord'),
        ),
        migrations.AddField(
            model_name='attendanceregularization',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendanceregularization',
            name='clock_in',
            field=models.TimeField(blank=True, help_text='Requested clock in', null=True),
        ),
        migrations.AlterField(
            model_name='attendanceregularization',
            name='clock_out',
            field=models.TimeField(blank=True, help_text='Requested clock out', null=True),
        ),
    ]
