# Generated by Django 6.0.1 on 2026-03-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0019_regularization_add_attendance_record_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ZK Device',
                'verbose_name_plural': 'ZK Devices',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='BiometricAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(help_text='Employee code from device', max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Check-In'), (1, 'Check-Out'), (2, 'Break-Out'), (3, 'Break-In'), (4, 'OT-In'), (5, 'OT-Out')], default=0)),
                ('verify_mode', models.IntegerField(default=0)),
                ('raw_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punches', to='hrm.zkdevice')),
            ],
            options={
                'verbose_name': 'Biometric Attendance',
                'verbose_name_plural': 'Biometric Attendances',
                'ordering': ['-timestamp'],
                'unique_together': {('pin', 'timestamp')},
            },
        ),
    ]
