# Generated by Django 6.0.1 on 2026-03-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0019_regularization_add_attendance_record_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZektoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(help_text='ZKTeco BioTime API base URL', max_length=500)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('auth_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zekto Setting',
                'verbose_name_plural': 'Zekto Settings',
            },
        ),
        migrations.CreateModel(
            name='BiometricAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('total_entries', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('device', 'Device'), ('manual', 'Manual'), ('import', 'Import')], default='device', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Biometric Attendance',
                'verbose_name_plural': 'Biometric Attendances',
                'ordering': ['-date'],
                'unique_together': {('employee_code', 'date')},
            },
        ),
    ]
