# Generated by Django 6.0.1 on 2026-03-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0020_zkdevice_biometricattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='zkdevice',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='zkdevice',
            name='face_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zkdevice',
            name='fingerprint_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zkdevice',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='zkdevice',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='zkdevice',
            name='transaction_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zkdevice',
            name='user_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
