# Generated by Django 6.0.1 on 2026-03-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0022_salarycomponent_employeesalary_payrollrun_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycomponent',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage_of_basic', '% of Basic Salary'), ('percentage_of_gross', '% of Gross Salary'), ('percentage_of_ctc', '% of CTC')], default='fixed', max_length=30),
        ),
    ]
