# Generated by Django 6.0.1 on 2026-03-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0023_salarycomponent_add_calculation_type_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='employee_salaries', to='hrm.salarycomponent'),
        ),
    ]
