# Generated by Django 6.0.1 on 2026-03-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0024_employeesalary_add_components_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrun',
            options={'ordering': ['-pay_date', '-created_at'], 'verbose_name': 'Payroll Run', 'verbose_name_plural': 'Payroll Runs'},
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='employee_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('bi_weekly', 'Bi-Weekly'), ('weekly', 'Weekly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='pay_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='pay_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
