# Generated by Django 6.0.1 on 2026-03-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0025_alter_payrollrun_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='generated_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payslip_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('downloaded', 'Downloaded'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
    ]
