# Generated by Django 6.0.1 on 2026-03-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0027_alter_employee_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
