# Generated by Django 6.0.1 on 2026-03-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0028_alter_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/'),
        ),
    ]
