# Generated by Django 6.0.1 on 2026-03-29 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0030_leavetype_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWeekend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekend_type', models.CharField(choices=[('weekend', 'Weekend'), ('holiday', 'Holiday')], default='weekend', max_length=10)),
                ('weekend_days', models.JSONField(default=list, help_text='List of day names e.g. ["saturday","sunday"]')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekend_assignments', to='hrm.employee')),
            ],
            options={
                'verbose_name': 'Employee Weekend',
                'verbose_name_plural': 'Employee Weekends',
                'ordering': ['-created_at'],
            },
        ),
    ]
