# Generated by Django 6.0.1 on 2026-03-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0032_advance_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='advance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Advance payment deduction for this pay period', max_digits=12),
        ),
    ]
