# Generated by Django 6.0.1 on 2026-03-30 21:50

import django.db.models.deletion
from django.db import migrations, models


def clear_text_shift_and_policy(apps, schema_editor):
    """Clear old text values from shift and attendance_policy before converting to FK.
    Setting to None won't work because the column is currently NOT NULL CharField,
    so we use raw SQL to set them to NULL directly."""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("UPDATE hrm_employee SET shift = NULL;")
        cursor.execute("UPDATE hrm_employee SET attendance_policy = NULL;")


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0033_add_advance_deduction_to_payslip'),
    ]

    operations = [
        # Step 1: Make existing CharField columns nullable first
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.CharField(max_length=100, blank=True, null=True, default=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='attendance_policy',
            field=models.CharField(max_length=100, blank=True, null=True, default=None),
        ),
        # Step 2: Clear old text values
        migrations.RunPython(clear_text_shift_and_policy, migrations.RunPython.noop),
        # Step 3: Convert to ForeignKey
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.shift'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='attendance_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.attendancepolicy'),
        ),
    ]
