# Generated by Django 6.0.1 on 2026-03-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0035_make_shift_end_time_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Whether this leave type is paid or unpaid'),
        ),
    ]
