# Generated by Django 6.0.1 on 2026-04-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0036_add_is_paid_to_leavetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='absent_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Absent-based salary deduction for this pay period', max_digits=12),
        ),
    ]
