# Generated by Django 6.0.1 on 2026-04-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0037_add_absent_deduction_to_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='pay_ot',
            field=models.BooleanField(default=False, help_text='Include overtime pay in payroll calculations'),
        ),
    ]
