# Generated by Django 6.0.1 on 2026-04-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0038_add_pay_ot_to_employeesalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='sandwich_rule',
            field=models.BooleanField(default=False, help_text='Apply sandwich rule: weekends/holidays between absences become unpaid'),
        ),
    ]
