# Generated by Django 6.0.1 on 2026-04-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0039_add_sandwich_rule_to_employeesalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycomponent',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('variable', 'Variable (Daily Pro-rata)'), ('percentage_of_basic', '% of Basic Salary'), ('percentage_of_gross', '% of Gross Salary'), ('percentage_of_ctc', '% of CTC')], default='fixed', max_length=30),
        ),
    ]
