# Generated by Django 5.2 on 2026-05-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0041_leaverequest_attachment_leavepolicy_leavebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='max_days_per_application',
            field=models.PositiveIntegerField(default=14, help_text='Maximum days allowed per leave application'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='min_days_per_application',
            field=models.PositiveIntegerField(default=1, help_text='Minimum days allowed per leave application'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='Whether leave applications under this policy require approval'),
        ),
    ]
