# Generated by Django 5.2 on 2026-05-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0042_leavepolicy_max_days_per_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='color',
            field=models.CharField(default='#22c55e', help_text='Hex color code for the leave type', max_length=7),
        ),
    ]
