# Generated by Django 5.2 on 2026-06-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0044_payslip_finalized_at_payslip_finalized_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes and internal calculation data', null=True),
        ),
    ]
