# Generated by Django 5.2 on 2026-07-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0045_payslip_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_divisor_type', models.CharField(choices=[('FIXED_30', 'Fixed 30 days (always divide by 30)'), ('ACTUAL_CYCLE_DAYS', 'Actual cycle days (calendar days in pay period)')], default='FIXED_30', help_text='Denominator used for DailyRate = MonthlySalary / Divisor', max_length=20)),
                ('weekend_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Pay multiplier for days worked on weekends (1=regular, 1.5=time-and-half, 2=double)', max_digits=4)),
                ('holiday_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Pay multiplier for days worked on public holidays', max_digits=4)),
                ('ot_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='OT pay multiplier per hour (Nepal Labor Act 2074 default: 1.5x)', max_digits=4)),
                ('shift_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, help_text='Standard working hours per day — used to derive HourlyRate from DailyRate', max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Setting',
                'verbose_name_plural': 'Payroll Settings',
            },
        ),
    ]
