# Generated by Django 5.2 on 2026-07-19 08:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0046_add_payroll_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of basic salary at generation', max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='salary_structure',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of earnings/deductions used in calculation'),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='ot_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='OT pay multiplier per hour (Nepal Labor Act 2074 default: 1.5x)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.50'))]),
        ),
        migrations.AlterField(
            model_name='payslipadjustment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shift',
            name='working_hours',
            field=models.DecimalField(decimal_places=1, default=8.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.CreateModel(
            name='HRMAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('record_id', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=50)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HRM Audit Log',
                'verbose_name_plural': 'HRM Audit Logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
