# Generated by Django 5.2 on 2026-07-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0048_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='half_day_hours',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Days worked at or below this many hours on this shift are marked Half Day', max_digits=4),
        ),
    ]
