# Generated by Django 5.2 on 2026-07-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0051_remove_attendancepolicy_half_day_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_regularized',
            field=models.BooleanField(default=False, help_text='Set when clock in/out was manually corrected (regularization approval or Fix Attendance). The biometric auto-sync will not overwrite these fields.'),
        ),
    ]
