# Generated by Django 5.2 on 2026-07-24 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0052_attendancerecord_is_regularized'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='last_fix_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='last_fixed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='last_fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_last_fixes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AttendanceFixLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_clock_in', models.TimeField(blank=True, null=True)),
                ('old_clock_out', models.TimeField(blank=True, null=True)),
                ('new_clock_in', models.TimeField(blank=True, null=True)),
                ('new_clock_out', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('fixed_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_logs', to='hrm.attendancerecord')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_fix_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Fix Log',
                'verbose_name_plural': 'Attendance Fix Logs',
                'ordering': ['-fixed_at'],
            },
        ),
    ]
