# Generated by Django 5.2 on 2026-07-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0053_attendancerecord_last_fix_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('session', 'Once per Browser Session'), ('refresh', 'Every Page Load / Refresh'), ('interval', 'Custom Time Interval')], default='refresh', max_length=20)),
                ('interval_minutes', models.PositiveIntegerField(default=60, help_text='Used only when mode is "Custom Time Interval". Minutes between re-shown alerts.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Alert Settings',
                'verbose_name_plural': 'Attendance Alert Settings',
            },
        ),
    ]
