# Generated by Django 5.2 on 2026-08-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0054_attendancealertsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_minutes', models.PositiveIntegerField(default=720, help_text='How often (in minutes) to automatically re-sync biometric attendance data. Default 720 = 12 hours.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Sync Settings',
                'verbose_name_plural': 'Attendance Sync Settings',
            },
        ),
    ]
