# Generated by Django 5.2 on 2026-08-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0055_attendance_sync_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceregularization',
            name='pre_regularization_state',
            field=models.JSONField(blank=True, default=dict, help_text='Attendance record values captured before this request was applied, so rejecting or deleting it can restore them'),
        ),
    ]
