# Generated by Django 5.2 on 2026-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0059_payslip_deleted_at_payslip_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='absent_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Worked hours at or below this count as Absent, even when both clock in and clock out were recorded.', max_digits=4),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='half_day_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Worked hours at or below this (and above the Absent threshold) count as Half Day. Anything above it counts as a Full Day.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='shift',
            name='half_day_hours',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Fallback Half Day threshold for this shift, only used when the employee has no effective Attendance Policy (see Attendance Policies for the primary setting).', max_digits=4),
        ),
    ]
