# Generated by Django 5.2 on 2026-08-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0060_attendancepolicy_absent_threshold_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zkdevice',
            name='force_resync_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
