# Generated by Django 5.2 on 2026-08-03 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(db_index=True, max_length=150)),
                ('role_snapshot', models.CharField(blank=True, default='', max_length=50)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('forwarded_chain', models.CharField(blank=True, default='', max_length=255)),
                ('network_label', models.CharField(blank=True, default='', help_text='Private LAN / loopback / public, derived from the IP.', max_length=80)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('browser', models.CharField(blank=True, default='', max_length=60)),
                ('browser_version', models.CharField(blank=True, default='', max_length=30)),
                ('operating_system', models.CharField(blank=True, default='', max_length=60)),
                ('os_version', models.CharField(blank=True, default='', max_length=30)),
                ('device_kind', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot / Crawler'), ('api', 'API Client'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('device_brand', models.CharField(blank=True, default='', max_length=40)),
                ('screen', models.CharField(blank=True, default='', help_text='Reported by the browser, e.g. 1920x1080.', max_length=24)),
                ('timezone_name', models.CharField(blank=True, default='', max_length=64)),
                ('language', models.CharField(blank=True, default='', max_length=32)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(choices=[('active', 'Active'), ('logout', 'Signed Out'), ('expired', 'Expired'), ('revoked', 'Revoked by Admin'), ('replaced', 'Replaced by New Session')], default='active', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_new_device', models.BooleanField(default=False)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('write_count', models.PositiveIntegerField(default=0)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentinel_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, db_index=True, default='anonymous', max_length=150)),
                ('actor_role', models.CharField(blank=True, default='', max_length=50)),
                ('event_type', models.CharField(choices=[('login', 'Sign In'), ('login_failed', 'Failed Sign In'), ('logout', 'Sign Out'), ('session_killed', 'Session Revoked'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('export', 'Exported'), ('import', 'Imported'), ('denied', 'Access Denied'), ('password', 'Credential Change'), ('permission', 'Permission Change'), ('job', 'Background Job'), ('integration', 'Integration Call'), ('error', 'System Error'), ('system', 'System Event')], db_index=True, default='system', max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('notice', 'Notice'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=10)),
                ('module', models.CharField(blank=True, db_index=True, default='', help_text='Owning app/area, e.g. dashboard, hrm, ncm.', max_length=50)),
                ('action', models.CharField(help_text='Human-readable summary shown in the stream.', max_length=255)),
                ('object_type', models.CharField(blank=True, db_index=True, default='', help_text='app_label.ModelName', max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('object_label', models.CharField(blank=True, default='', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{field: {"old": ..., "new": ...}} for updates.')),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('view_name', models.CharField(blank=True, default='', max_length=160)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_kind', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot / Crawler'), ('api', 'API Client'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('browser', models.CharField(blank=True, default='', max_length=60)),
                ('operating_system', models.CharField(blank=True, default='', max_length=60)),
                ('risk_score', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='0–100. Drives the risk column and alerting.')),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Free-form extras from the caller.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentinel_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sentinel.devicesession')),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KnownDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=160)),
                ('browser', models.CharField(blank=True, default='', max_length=60)),
                ('operating_system', models.CharField(blank=True, default='', max_length=60)),
                ('device_kind', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot / Crawler'), ('api', 'API Client'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False, help_text='Sign-ins from this device raise a critical alert.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentinel_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddField(
            model_name='devicesession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='sentinel.knowndevice'),
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new_device', 'Unrecognised Device'), ('brute_force', 'Repeated Failed Sign-ins'), ('off_hours', 'Off-hours Access'), ('bulk_delete', 'Bulk Deletion'), ('denial_storm', 'Repeated Access Denials'), ('permission_change', 'Permission Escalation'), ('concurrent', 'Concurrent Sessions'), ('blocked_device', 'Sign-in from Blocked Device'), ('data_export', 'Large Data Export')], db_index=True, max_length=24)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('notice', 'Notice'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='warning', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ack', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=10)),
                ('subject_username', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='sentinel.auditevent')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentinel_resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='sentinel.devicesession')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentinel_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Alert',
                'verbose_name_plural': 'Security Alerts',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_page_views', models.BooleanField(default=True, help_text='Record read-only page visits (GET). Turn off to log writes only.')),
                ('capture_field_diffs', models.BooleanField(default=True, help_text='Record before/after values on every tracked model change.')),
                ('capture_anonymous', models.BooleanField(default=False, help_text='Record activity from signed-out visitors (storefront traffic).')),
                ('retention_days', models.PositiveIntegerField(default=180, help_text='Events older than this are removed by the sentinel_prune command.')),
                ('page_view_retention_days', models.PositiveIntegerField(default=30, help_text='Low-value page-view rows expire sooner than write events.')),
                ('failed_login_threshold', models.PositiveIntegerField(default=5, help_text='Failed sign-ins from one IP within the window before an alert is raised.')),
                ('failed_login_window_minutes', models.PositiveIntegerField(default=15)),
                ('bulk_delete_threshold', models.PositiveIntegerField(default=10, help_text='Deletions by one user within an hour before an alert is raised.')),
                ('denial_threshold', models.PositiveIntegerField(default=8, help_text='Permission denials by one user within an hour before an alert is raised.')),
                ('office_hours_start', models.TimeField(default='07:00', help_text='Activity outside this window is flagged as off-hours (Nepal time).')),
                ('office_hours_end', models.TimeField(default='21:00')),
                ('alert_on_off_hours', models.BooleanField(default=True)),
                ('alert_on_new_device', models.BooleanField(default=True)),
                ('excluded_paths', models.TextField(blank=True, default='/static/\n/media/\n/iclock/\n/favicon.ico', help_text='One URL prefix per line. Requests starting with these are never recorded.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentinel_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vault Settings',
                'verbose_name_plural': 'Vault Settings',
            },
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['-created_at', 'event_type'], name='sentinel_au_created_a2d9df_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', '-created_at'], name='sentinel_au_actor_i_2ce3d7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['object_type', 'object_id'], name='sentinel_au_object__6c51bd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['module', '-created_at'], name='sentinel_au_module_1a20d3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['-risk_score', '-created_at'], name='sentinel_au_risk_sc_f0144f_idx'),
        ),
        migrations.AddIndex(
            model_name='knowndevice',
            index=models.Index(fields=['user', '-last_seen'], name='sentinel_kn_user_id_ae768e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowndevice',
            unique_together={('user', 'fingerprint')},
        ),
        migrations.AddIndex(
            model_name='devicesession',
            index=models.Index(fields=['is_active', '-last_activity'], name='sentinel_de_is_acti_021a91_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesession',
            index=models.Index(fields=['user', '-started_at'], name='sentinel_de_user_id_d3bde9_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['status', '-last_seen_at'], name='sentinel_se_status_230e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['kind', '-created_at'], name='sentinel_se_kind_fc5535_idx'),
        ),
    ]
