# Generated by Django 5.2 on 2026-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultsettings',
            name='excluded_paths',
            field=models.TextField(blank=True, default='/static/\n/media/\n/iclock/\n/favicon.ico\n/chat/api/unread-count/\n/api/active-notice/\n/hrm/attendance/incomplete/?count_only=1', help_text='One URL prefix per line. Requests starting with these are never recorded. Include a ?query fragment to match only that variant of a path.'),
        ),
    ]
