# Generated by Django 5.2 on 2026-08-03 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0003_exclude_background_pollers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultsettings',
            name='office_hours_end',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AlterField(
            model_name='vaultsettings',
            name='office_hours_start',
            field=models.TimeField(default=datetime.time(7, 0), help_text='Activity outside this window is flagged as off-hours (Nepal time).'),
        ),
    ]
