# Generated by Django 5.2 on 2026-08-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_and_drop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pndbulklog',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pndbulklog',
            name='selected_order_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pndbulklog',
            name='worker_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pndbulklog',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='processing', max_length=20),
        ),
    ]
