# Generated by Django 6.0.1 on 2026-01-31 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order_deleted_at_order_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('return_reason', models.CharField(choices=[('defective', 'Defective/Damaged Product'), ('wrong_item', 'Wrong Item Received'), ('not_as_described', 'Not as Described'), ('size_issue', 'Size/Fit Issue'), ('quality_issue', 'Quality Issue'), ('changed_mind', 'Changed Mind'), ('ordered_by_mistake', 'Ordered by Mistake'), ('late_delivery', 'Late Delivery'), ('other', 'Other')], max_length=50)),
                ('return_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Item Received'), ('inspecting', 'Quality Inspection'), ('approved_refund', 'Approved for Refund'), ('approved_exchange', 'Approved for Exchange'), ('refunded', 'Refunded'), ('exchanged', 'Exchanged'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('refund_type', models.CharField(choices=[('full_refund', 'Full Refund'), ('partial_refund', 'Partial Refund'), ('store_credit', 'Store Credit'), ('exchange', 'Exchange for Another Item'), ('no_refund', 'No Refund')], default='full_refund', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('restocking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('condition_received', models.CharField(blank=True, choices=[('new', 'New/Unused'), ('opened', 'Opened but Unused'), ('used', 'Used - Good Condition'), ('damaged', 'Damaged'), ('defective', 'Defective')], max_length=50, null=True)),
                ('quality_check_notes', models.TextField(blank=True, null=True)),
                ('quality_checked_at', models.DateTimeField(blank=True, null=True)),
                ('return_image_1', models.ImageField(blank=True, null=True, upload_to='returns/')),
                ('return_image_2', models.ImageField(blank=True, null=True, upload_to='returns/')),
                ('return_image_3', models.ImageField(blank=True, null=True, upload_to='returns/')),
                ('customer_notes', models.TextField(blank=True, help_text="Customer's reason for return", null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes', null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='dashboard.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='dashboard.order')),
                ('quality_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checked_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_quantity', models.PositiveIntegerField(default=1)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('restocked', models.BooleanField(default=False)),
                ('restocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('product_variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.productvariation')),
                ('restocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.returnrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='dashboard.returnrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
