# Generated by Django 6.0.1 on 2026-02-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_returnrequest_deleted_at_returnrequest_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
