# Generated by Django 6.0.1 on 2026-02-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_order_barcode_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='variation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
