# Generated by Django 6.0.1 on 2026-02-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_productvariation_variation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='logistics_provider',
            new_name='logistics',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='processing', max_length=50),
        ),
    ]
