# Generated by Django 6.0.1 on 2026-02-02 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_logistics_provider_order_logistics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('logistics', models.CharField(choices=[('ncm', 'NCM'), ('sundarijal', 'Sundarijal'), ('express', 'Express'), ('local', 'Local Delivery'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched')], default='dispatched', max_length=50)),
                ('total_orders', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatches', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_order_id', models.CharField(db_index=True, max_length=100)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.dispatch')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_items', to='dashboard.order')),
            ],
            options={
                'verbose_name': 'Dispatch Item',
                'verbose_name_plural': 'Dispatch Items',
                'ordering': ['scanned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['-created_at'], name='dashboard_d_created_8c6a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['batch_number'], name='dashboard_d_batch_n_11dbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['is_deleted'], name='dashboard_d_is_dele_a569f9_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchitem',
            index=models.Index(fields=['scanned_order_id'], name='dashboard_d_scanned_f8677a_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchitem',
            index=models.Index(fields=['scanned_at'], name='dashboard_d_scanned_eda281_idx'),
        ),
    ]
