# Generated by Django 6.0.1 on 2026-02-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_dispatch_dispatchitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_custom_product',
            field=models.BooleanField(default=False, help_text='Mark as custom/quick sale product'),
        ),
    ]
