# Generated by Django 6.0.1 on 2026-02-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_product_options_product_is_custom_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ncm_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ncm_delivery_type',
            field=models.CharField(choices=[('Door2Door', 'Door to Door'), ('Branch2Door', 'Branch to Door'), ('Door2Branch', 'Door to Branch'), ('Branch2Branch', 'Branch to Branch')], default='Door2Door', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='ncm_destination_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='ncm_from_branch',
            field=models.CharField(blank=True, default='TINKUNE', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='ncm_order_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ncm_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='package_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in kg', max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
