# Generated by Django 6.0.1 on 2026-02-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_order_ncm_created_at_order_ncm_delivery_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_type', models.CharField(choices=[('payment', 'Payment Setup'), ('status', 'Status Setup')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setup',
                'verbose_name_plural': 'Setups',
                'ordering': ['setup_type', 'name'],
                'unique_together': {('setup_type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_setup',
            field=models.ForeignKey(blank=True, limit_choices_to={'setup_type': 'payment'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_payment', to='dashboard.setup'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_setup',
            field=models.ForeignKey(blank=True, limit_choices_to={'setup_type': 'status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_status', to='dashboard.setup'),
        ),
    ]
