# Generated by Django 6.0.1 on 2026-02-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_setup_order_payment_setup_order_status_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status_setup',
            field=models.ForeignKey(blank=True, limit_choices_to={'setup_type': 'payment_status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_payment_status', to='dashboard.setup'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='setup_type',
            field=models.CharField(choices=[('payment', 'Payment Setup'), ('status', 'Status Setup'), ('payment_status', 'Payment Status Setup')], max_length=50),
        ),
    ]
