# Generated by Django 6.0.1 on 2026-02-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_order_payment_status_setup_alter_setup_setup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
