# Generated by Django 6.0.1 on 2026-02-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_customer_phone_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=0, help_text='Alert when stock falls to or below this value'),
        ),
    ]
