# Generated by Django 6.0.1 on 2026-02-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='low_stock_threshold',
            field=models.IntegerField(default=0, help_text='Alert when variation stock falls to or below this value'),
        ),
    ]
