# Generated by Django 6.0.1 on 2026-02-18 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_branch_order_cod_collected_order_delivery_charge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_collected',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount collected as COD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='NCM delivery charge or logistics charge', max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='expense_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other operational expenses', max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='package_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in kg', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='partial_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='StaffPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('successful_orders', models.IntegerField(default=0)),
                ('return_count', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage 0-100', max_digits=5)),
                ('period_start', models.DateField(auto_now_add=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Performance',
                'verbose_name_plural': 'Staff Performance Metrics',
                'ordering': ['-success_rate', '-total_revenue'],
            },
        ),
    ]
