# Generated by Django 6.0.1 on 2026-02-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_fix_decimal_field_overflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_collected',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount collected as COD', max_digits=18),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='NCM delivery charge or logistics charge', max_digits=18),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='order',
            name='expense_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other operational expenses', max_digits=18),
        ),
        migrations.AlterField(
            model_name='order',
            name='partial_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
