# Generated by Django 6.0.1 on 2026-02-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_increase_decimal_max_digits_to_18'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='damaged_qty',
            field=models.PositiveIntegerField(default=0, help_text='Quantity that is damaged/defective'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='good_qty',
            field=models.PositiveIntegerField(default=0, help_text='Quantity in good/resellable condition'),
        ),
    ]
