# Generated by Django 6.0.1 on 2026-02-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_add_good_qty_damaged_qty_to_returnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('defective', 'Defective/Damaged Product'), ('wrong_item', 'Wrong Item Received'), ('not_as_described', 'Not as Described'), ('size_issue', 'Size/Fit Issue'), ('quality_issue', 'Quality Issue'), ('changed_mind', 'Changed Mind'), ('ordered_by_mistake', 'Ordered by Mistake'), ('late_delivery', 'Late Delivery'), ('other', 'Other')], default='', max_length=50),
        ),
    ]
