# Generated by Django 6.0.1 on 2026-02-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_make_return_reason_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, help_text='Groups bulk-created returns together', max_length=50, null=True),
        ),
    ]
