# Generated by Django 6.0.1 on 2026-02-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_add_batch_id_to_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='restocking_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
