# Generated by Django 6.0.1 on 2026-02-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_add_staff_target_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
