# Generated by Django 6.0.1 on 2026-02-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_change_tax_percent_default_to_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='setup_type',
            field=models.CharField(choices=[('payment', 'Payment Setup'), ('status', 'Status Setup'), ('payment_status', 'Payment Status Setup'), ('order_source', 'Order Source')], max_length=50),
        ),
    ]
