# Generated by Django 6.0.1 on 2026-03-03 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_orderadminnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'Simple Product'), ('variable', 'Variable Product'), ('bundle', 'Bundle/Combo Product')], default='simple', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Simple product this purchase is for', on_delete=django.db.models.deletion.CASCADE, related_name='product_purchases', to='dashboard.product')),
            ],
            options={
                'verbose_name': 'Product Purchase',
                'verbose_name_plural': 'Product Purchases',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='BundleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.PositiveIntegerField(default=1, help_text='How many units of this component are needed per bundle')),
                ('bundle_product', models.ForeignKey(help_text='The bundle/combo product', on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='dashboard.product')),
                ('component_product', models.ForeignKey(help_text='The child component product', on_delete=django.db.models.deletion.CASCADE, related_name='part_of_bundles', to='dashboard.product')),
            ],
            options={
                'verbose_name': 'Bundle Component',
                'verbose_name_plural': 'Bundle Components',
                'unique_together': {('bundle_product', 'component_product')},
            },
        ),
    ]
