# Generated by Django 6.0.1 on 2026-03-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_product_product_type_productpurchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Cost Price'), ('variable', 'Variable Cost Price')], default='fixed', max_length=10),
        ),
    ]
