# Generated by Django 6.0.1 on 2026-03-10 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_product_cost_price_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_type', models.CharField(choices=[('called_no_answer', 'Called - No Answer'), ('called_answered', 'Called - Answered'), ('whatsapp_sent', 'WhatsApp Sent'), ('email_sent', 'Email Sent'), ('custom_note', 'Custom Note')], default='custom_note', max_length=30)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='dashboard.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Follow-Up',
                'verbose_name_plural': 'Order Follow-Ups',
                'ordering': ['-created_at'],
            },
        ),
    ]
