# Generated by Django 6.0.1 on 2026-03-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_orderfollowup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='next_followup_date',
            field=models.DateField(blank=True, help_text='Scheduled next follow-up date', null=True),
        ),
    ]
