# Generated by Django 6.0.1 on 2026-03-11 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_add_next_followup_date_to_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='followup_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='followup_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='followup_type',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('visit', 'Visit')], max_length=20, null=True),
        ),
    ]
