# Generated by Django 6.0.1 on 2026-03-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_add_followup_fields_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pnd_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pnd_destination_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='pnd_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pnd_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='pnd_tracking_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='logistics',
            field=models.CharField(choices=[('ncm', 'NCM'), ('pick_and_drop', 'Pick and Drop'), ('sundarijal', 'Sundarijal'), ('express', 'Express'), ('local', 'Local Delivery'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics',
            field=models.CharField(blank=True, choices=[('ncm', 'NCM'), ('pick_and_drop', 'Pick and Drop'), ('sundarijal', 'Sundarijal'), ('express', 'Express'), ('local', 'Local Delivery'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
