# Generated by Django 6.0.1 on 2026-03-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_order_pnd_created_at_order_pnd_destination_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default selection for this setup type in order forms'),
        ),
    ]
