# Generated by Django 6.0.1 on 2026-03-20 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_setup_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='product_variation',
            field=models.ForeignKey(blank=True, help_text='Specific variation for variable products', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='dashboard.productvariation'),
        ),
    ]
