# Generated by Django 6.0.1 on 2026-03-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_add_variation_to_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchitem',
            name='dispatch_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('not_found', 'Not Found')], db_index=True, default='not_found', max_length=20),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
