# Generated by Django 6.0.1 on 2026-04-03 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_dispatchitem_dispatch_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(help_text='Descriptive name for this API configuration', max_length=100)),
                ('logistics_provider', models.CharField(choices=[('ncm', 'NCM Logistics'), ('pick_and_drop', 'Pick and Drop'), ('other', 'Other')], max_length=50)),
                ('api_key', models.CharField(max_length=500)),
                ('api_secret', models.CharField(blank=True, default='', help_text='API Secret (required for Pick and Drop)', max_length=500)),
                ('base_urls', models.JSONField(default=list, help_text='List of base URLs for this API')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logistics API Configuration',
                'verbose_name_plural': 'Logistics API Configurations',
                'ordering': ['logistics_provider', 'api_name'],
            },
        ),
    ]
