# Generated by Django 6.0.1 on 2026-04-03 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_logisticsapiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='api_config',
            field=models.ForeignKey(blank=True, help_text='Selected logistics API configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dashboard.logisticsapiconfig'),
        ),
    ]
