# Generated by Django 6.0.1 on 2026-04-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_order_api_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Trendy Shopping', max_length=200)),
                ('tagline', models.CharField(blank=True, default='', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('theme', models.CharField(choices=[('default', 'Default Blue'), ('dark', 'Dark Mode'), ('purple', 'Purple Elegance'), ('green', 'Forest Green'), ('orange', 'Sunset Orange'), ('red', 'Ruby Red'), ('teal', 'Teal Ocean'), ('indigo', 'Deep Indigo')], default='default', max_length=30)),
                ('primary_color', models.CharField(default='#5e72e4', max_length=7)),
                ('secondary_color', models.CharField(default='#825ee4', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Setup',
                'verbose_name_plural': 'Company Setup',
            },
        ),
    ]
