# Generated by Django 6.0.1 on 2026-04-12 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_add_company_setup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RTVOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(help_text='NCM order ID')),
                ('comment', models.TextField(blank=True, default='')),
                ('vendor_return', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtv_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RTV Order',
                'verbose_name_plural': 'RTV Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
