# Generated by Django 6.0.1 on 2026-04-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_rtvorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtvorder',
            name='order_id',
            field=models.IntegerField(help_text='NCM order ID', unique=True),
        ),
    ]
