# Generated by Django 6.0.1 on 2026-04-15 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_add_unique_to_rtvorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtvorder',
            name='api_config',
            field=models.ForeignKey(blank=True, help_text='Which API config (portal) this RTV belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtv_orders', to='dashboard.logisticsapiconfig'),
        ),
    ]
