# Generated by Django 6.0.1 on 2026-04-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_rtv_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_status',
            field=models.CharField(blank=True, choices=[('', 'Not Exchanged'), ('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='ncm_exchange_cust_order',
            field=models.IntegerField(blank=True, help_text='NCM exchange customer order ID', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ncm_exchange_ven_order',
            field=models.IntegerField(blank=True, help_text='NCM exchange vendor order ID', null=True),
        ),
    ]
