# Generated by Django 6.0.1 on 2026-04-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_order_exchange_status_order_ncm_exchange_cust_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rtvorder',
            options={'ordering': ['-rtv_marked_at', '-created_at'], 'verbose_name': 'RTV Order', 'verbose_name_plural': 'RTV Orders'},
        ),
        migrations.AddField(
            model_name='rtvorder',
            name='rtv_marked_at',
            field=models.DateTimeField(blank=True, help_text='When NCM staff marked this order as vendor_return (from RTV comment added_time)', null=True),
        ),
    ]
