# Generated by Django 6.0.1 on 2026-04-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_rtv_marked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtvorder',
            name='cod_charge',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rtvorder',
            name='delivery_charge',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rtvorder',
            name='from_branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rtvorder',
            name='last_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rtvorder',
            name='receiver_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rtvorder',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtvorder',
            name='receiver_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rtvorder',
            name='to_branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rtvorder',
            name='tracking_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
