# Generated by Django 6.0.1 on 2026-04-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_rtv_order_ncm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtvorder',
            name='product_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
