# Generated by Django 5.2 on 2026-04-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_rtv_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='backordered_qty',
            field=models.IntegerField(default=0, help_text='Units ordered beyond available stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='backorders_allowed',
            field=models.BooleanField(default=False, help_text='Allow orders beyond available stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved_qty',
            field=models.IntegerField(default=0, help_text='Units locked by unshipped orders'),
        ),
    ]
