# Generated by Django 5.2 on 2026-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_backorder_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sync_interval', models.PositiveIntegerField(default=14400, help_text='How often (in seconds) to auto-sync orders from NCM. Default: 14400 (4 hours).')),
                ('webhook_check_interval', models.PositiveIntegerField(default=30, help_text='How often (in seconds) to check for pending webhook updates. Default: 30.')),
                ('ncm_api_timeout', models.PositiveIntegerField(default=30, help_text='Timeout (in seconds) for each NCM API request. Default: 30.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Settings',
                'verbose_name_plural': 'API Settings',
            },
        ),
    ]
