# Generated by Django 5.2 on 2026-05-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_api_settings_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtvorder',
            name='rtv_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('item_received', 'Item Received'), ('in_transit', 'In Transit'), ('returned_to_vendor', 'Returned to Vendor'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', help_text='Manually managed RTV status (not fetched from NCM)', max_length=30),
        ),
    ]
