# Generated by Django 5.2 on 2026-05-07 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_rtv_status_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtvorder',
            name='rtv_status',
        ),
        migrations.AlterField(
            model_name='rtvorder',
            name='rtv_status_option',
            field=models.ForeignKey(blank=True, help_text='Manually set status for this RTV order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtv_orders', to='dashboard.rtvstatusoption'),
        ),
        migrations.AlterField(
            model_name='rtvstatusoption',
            name='color',
            field=models.CharField(default='#667eea', help_text='Hex color code, e.g. #667eea', max_length=7),
        ),
    ]
