# Generated by Django 5.2 on 2026-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_maintenance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderactivitylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data for specific action types (e.g., old customer details for redirections)', null=True),
        ),
        migrations.AlterField(
            model_name='orderactivitylog',
            name='action_type',
            field=models.CharField(choices=[('created', 'Order Created'), ('status_changed', 'Status Changed'), ('payment_changed', 'Payment Status Changed'), ('tracking_added', 'Tracking Number Added'), ('tracking_updated', 'Tracking Number Updated'), ('notes_added', 'Admin Notes Added'), ('notes_updated', 'Admin Notes Updated'), ('updated', 'Order Updated'), ('redirected', 'Order Redirected')], max_length=50),
        ),
    ]
