# Generated by Django 5.2 on 2026-05-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_add_metadata_to_orderactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTVStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#667eea', help_text='Hex color code (e.g. #667eea)', max_length=7)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RTV Status',
                'verbose_name_plural': 'RTV Statuses',
                'ordering': ['name'],
            },
        ),
    ]
