# Generated by Django 5.2 on 2026-05-31 11:42
# Converts rtv_status from CharField to ForeignKey to RTVStatus

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_create_rtvstatus_table'),
    ]

    operations = [
        # Drop the old varchar(30) rtv_status column
        migrations.RunSQL(
            sql="ALTER TABLE dashboard_rtvorder DROP COLUMN rtv_status",
            reverse_sql="ALTER TABLE dashboard_rtvorder ADD COLUMN rtv_status VARCHAR(30) DEFAULT '' NOT NULL",
        ),
        # Add the new ForeignKey column
        migrations.AddField(
            model_name='rtvorder',
            name='rtv_status',
            field=models.ForeignKey(
                blank=True,
                help_text='Locally assigned status for this RTV',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='rtv_orders',
                to='dashboard.rtvstatus',
            ),
        ),
    ]
