# Generated by Django 5.2 on 2026-06-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_fix_rtv_status_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='backordered_qty',
            field=models.IntegerField(default=0, help_text='Units waiting on new stock'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reserved_qty',
            field=models.IntegerField(default=0, help_text='Units filled from real stock'),
        ),
    ]
