# Generated by Django 5.2 on 2026-06-05 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_orderitem_backordered_qty_orderitem_reserved_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Date the product expires', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(blank=True, help_text='Date the product was manufactured', null=True),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(default=0, help_text='Remaining units in this batch')),
                ('initial_quantity', models.IntegerField(default=0, help_text='Original units when batch was created')),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='dashboard.product')),
            ],
            options={
                'verbose_name': 'Product Batch',
                'verbose_name_plural': 'Product Batches',
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
    ]
