# Generated by Django 5.2 on 2026-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_globalnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnotice',
            name='display_from',
            field=models.DateTimeField(blank=True, help_text='When to start showing the notice', null=True),
        ),
        migrations.AlterField(
            model_name='globalnotice',
            name='display_until',
            field=models.DateTimeField(blank=True, help_text='When to stop showing the notice', null=True),
        ),
    ]
