# Generated by Django 5.2 on 2026-06-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_globalnotice_display_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnotice',
            name='display_frequency',
            field=models.CharField(choices=[('every_refresh', 'Every Refresh'), ('once_per_session', 'Once Per Session'), ('once_per_hour', 'Once Per Hour'), ('once_per_day', 'Once Per Day'), ('once_per_week', 'Once Per Week'), ('once_only', 'Once Only')], default='every_refresh', help_text='How often to show the notice to a user', max_length=20),
        ),
    ]
