# Generated by Django 5.2 on 2026-06-22 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_globalnotice_display_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('lead_source', models.CharField(blank=True, max_length=100)),
                ('followup_1', models.CharField(blank=True, max_length=255)),
                ('followup_2', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
