# Generated by Django 5.2 on 2026-06-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
