# Generated by Django 5.2 on 2026-06-22 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_followup_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='follow_ups_multi', to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups_single', to='dashboard.product'),
        ),
    ]
