# Generated by Django 5.2 on 2026-06-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_contentaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255)),
                ('report_date', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_posts', models.TextField(blank=True, null=True)),
                ('views', models.TextField(blank=True, null=True)),
                ('likes', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('follower_growth', models.TextField(blank=True, null=True)),
                ('punctuality', models.TextField(blank=True, null=True)),
                ('behaviour', models.TextField(blank=True, null=True)),
                ('leave_and_wfh', models.TextField(blank=True, null=True)),
                ('notes_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Staff Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
