# Generated by Django 5.2 on 2026-06-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_staffreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='setup_type',
            field=models.CharField(choices=[('payment', 'Payment Setup'), ('status', 'Status Setup'), ('payment_status', 'Payment Status Setup'), ('order_source', 'Order Source'), ('followup_status', 'Follow-up Status')], max_length=50),
        ),
    ]
