# Generated by Django 5.2 on 2026-06-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_alter_setup_setup_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentaccount',
            options={'ordering': ['order', '-created_at'], 'verbose_name_plural': 'Content Accounts'},
        ),
        migrations.AddField(
            model_name='contentaccount',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
