# Generated by Django 5.2 on 2026-06-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_followuplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='product_variations',
            field=models.ManyToManyField(blank=True, related_name='follow_ups_multi', to='dashboard.productvariation'),
        ),
    ]
