# Generated by Django 5.2 on 2026-07-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_followup_product_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
