# Generated by Django 5.2 on 2026-07-08 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_followup_updated_at_followup_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewing', 'Viewing'), ('typing', 'Typing')], max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='dashboard.followup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['last_seen'], name='dashboard_f_last_se_75f938_idx')],
                'unique_together': {('followup', 'user')},
            },
        ),
    ]
