# Generated by Django 5.2 on 2026-07-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_followuppresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code for badges', max_length=50, null=True),
        ),
    ]
