# Generated by Django 5.2 on 2026-07-27 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_mediacategory_mediaasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='source_asset',
            field=models.ForeignKey(blank=True, help_text='Media Library asset this gallery image was copied from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_uses', to='dashboard.mediaasset'),
        ),
    ]
