# Generated by Django 5.2 on 2026-07-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_productimage_source_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='bulk_sync_included_statuses',
            field=models.JSONField(blank=True, default=list, help_text='Order statuses eligible for the background NCM bulk status sync. Empty = use default (sync all except cancelled/delivered/return/returned/return_initiated/return_approved).'),
        ),
    ]
