# Generated by Django 5.2 on 2026-07-30 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_return_processing_status_setup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderactivitylog',
            name='event_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Provider-reported event time (NCM added_time / webhook timestamp). NULL for locally-originated actions.', null=True),
        ),
        migrations.AddField(
            model_name='rtvorder',
            name='ncm_created_date',
            field=models.DateTimeField(blank=True, help_text="NCM's order creation date. Kept for filtering/reference only — this is NOT when the RTV was marked.", null=True),
        ),
        migrations.AddField(
            model_name='rtvorder',
            name='rtv_marked_at_checked_at',
            field=models.DateTimeField(blank=True, help_text="Last time we asked NCM for this order's RTV date. Repair passes take the least-recently-checked rows so a bounded batch size converges.", null=True),
        ),
        migrations.AddField(
            model_name='rtvorder',
            name='rtv_marked_at_source',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('order_created', 'NCM order created_date (wrong — legacy)'), ('status_timeline', 'NCM status timeline return step (approximate)'), ('ncm_staff_comment', 'Latest NCM Staff comment (approximate)'), ('comment', 'NCM "RTV marked" comment'), ('manual', 'Marked locally via this app')], db_index=True, default='', help_text='Where rtv_marked_at came from; drives which rows get re-verified', max_length=20),
        ),
        migrations.AddIndex(
            model_name='orderactivitylog',
            index=models.Index(fields=['order', '-created_at'], name='oal_order_created_idx'),
        ),
    ]
