# Generated by Django 5.2 on 2026-07-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_backfill_rtv_marked_at_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='bulk_sync_fetch_event_times',
            field=models.BooleanField(default=True, help_text="During background sync, fetch NCM's real event time for each order whose status changed (one extra API request per changed order). When off, activity log entries are timestamped with the sync run's own time instead."),
        ),
        migrations.AlterField(
            model_name='rtvorder',
            name='rtv_marked_at_source',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('order_created', 'NCM order created_date (wrong — legacy)'), ('status_timeline', 'NCM status timeline return step (approximate)'), ('ncm_staff_comment', 'Latest NCM Staff comment (approximate)'), ('comment', 'NCM "RTV marked" comment'), ('webhook', 'NCM order_marked_rtv webhook'), ('manual', 'Marked locally via this app')], db_index=True, default='', help_text='Where rtv_marked_at came from; drives which rows get re-verified', max_length=20),
        ),
    ]
