# Generated by Django 5.2 on 2026-08-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_apisettings_bulk_sync_fetch_event_times_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_pill_text', models.CharField(blank=True, default='The commerce OS for Nepal', max_length=100)),
                ('hero_headline', models.CharField(blank=True, default='Run your entire shop from one system', max_length=200)),
                ('hero_subtext', models.TextField(blank=True, default='Online and offline selling, inventory, courier logistics, customer messaging and your team — one connected infrastructure instead of six disconnected tools.')),
                ('hero_cta_primary_text', models.CharField(blank=True, default='Start selling', max_length=50)),
                ('hero_cta_primary_link', models.CharField(blank=True, default='', max_length=200)),
                ('hero_cta_secondary_text', models.CharField(blank=True, default='Explore platform', max_length=50)),
                ('hero_cta_secondary_link', models.CharField(blank=True, default='#platform', max_length=200)),
                ('hero_note_text', models.CharField(blank=True, default='Nepali time zone, rupee amounts and local courier networks out of the box', max_length=200)),
                ('trusted_label', models.CharField(blank=True, default='Trusted by growing Nepali brands', max_length=150)),
                ('solutions_eyebrow', models.CharField(blank=True, default='Solutions', max_length=50)),
                ('solutions_heading', models.CharField(blank=True, default='Choose how you want to sell', max_length=200)),
                ('solutions_subtext', models.TextField(blank=True, default='Whether you sell through Instagram DMs, a storefront, or a counter in Kathmandu — it runs on the same stock and the same orders.')),
                ('solution_card1_title', models.CharField(blank=True, default='Online sellers', max_length=100)),
                ('solution_card1_text', models.TextField(blank=True, default='Storefront, Instagram and Facebook messaging, two-way Google Sheets sync, courier handoff and COD tracking — all against one set of stock.')),
                ('solution_card2_title', models.CharField(blank=True, default='Physical stores', max_length=100)),
                ('solution_card2_text', models.TextField(blank=True, default='POS counter billing, barcode-driven product lookup and per-branch order tracking — sharing the same inventory as everything you sell online.')),
                ('platform_eyebrow', models.CharField(blank=True, default='Platform', max_length=50)),
                ('platform_heading', models.CharField(blank=True, default='A full selling infrastructure', max_length=200)),
                ('platform_subtext', models.CharField(blank=True, default='Every part of the operation — not just a storefront.', max_length=250)),
                ('integrations_eyebrow', models.CharField(blank=True, default='Integrations', max_length=50)),
                ('integrations_heading', models.CharField(blank=True, default='Connected to the tools you already use', max_length=200)),
                ('cta_heading', models.CharField(blank=True, default='Ready to run it all from one place?', max_length=200)),
                ('cta_subtext', models.CharField(blank=True, default='Sign in to your dashboard, or browse the storefront to see it in action.', max_length=250)),
                ('cta_primary_text', models.CharField(blank=True, default='Get started', max_length=50)),
                ('cta_secondary_text', models.CharField(blank=True, default='Visit the store', max_length=50)),
                ('business_address', models.CharField(blank=True, default='', max_length=255)),
                ('business_pan', models.CharField(blank=True, default='', max_length=100)),
                ('business_contact', models.CharField(blank=True, default='', max_length=150)),
                ('social_instagram', models.URLField(blank=True, default='', max_length=300)),
                ('social_facebook', models.URLField(blank=True, default='', max_length=300)),
                ('social_tiktok', models.URLField(blank=True, default='', max_length=300)),
                ('social_whatsapp', models.URLField(blank=True, default='', max_length=300)),
                ('social_email', models.EmailField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Setup',
                'verbose_name_plural': 'Landing Page Setup',
            },
        ),
        migrations.CreateModel(
            name='LandingFeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('platform', 'Platform feature'), ('integration', 'Integration')], default='platform', max_length=15)),
                ('icon', models.CharField(default='fas fa-star', help_text='Font Awesome class, e.g. "fas fa-box"', max_length=60)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_cards', to='dashboard.landingpagesettings')),
            ],
            options={
                'verbose_name': 'Landing Feature Card',
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingBrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='landing/brands/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_logos', to='dashboard.landingpagesettings')),
            ],
            options={
                'verbose_name': 'Landing Brand Logo',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingStatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, default='', max_length=100)),
                ('dot_color', models.CharField(blank=True, choices=[('amber', 'Amber'), ('green', 'Green'), ('blue', 'Blue'), ('', 'None')], default='', max_length=10)),
                ('group', models.CharField(choices=[('primary', 'Top row (dot + right-aligned value)'), ('secondary', 'Stock row (below divider)')], default='primary', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_items', to='dashboard.landingpagesettings')),
            ],
            options={
                'verbose_name': 'Landing Stat Item',
                'ordering': ['group', 'order', 'id'],
            },
        ),
    ]
