# Generated by Django 5.2 on 2026-08-02 09:46

from django.db import migrations


def seed_landing_defaults(apps, schema_editor):
    LandingPageSettings = apps.get_model('dashboard', 'LandingPageSettings')
    LandingStatItem = apps.get_model('dashboard', 'LandingStatItem')
    LandingBrandLogo = apps.get_model('dashboard', 'LandingBrandLogo')
    LandingFeatureCard = apps.get_model('dashboard', 'LandingFeatureCard')

    settings, created = LandingPageSettings.objects.get_or_create(pk=1)
    if not created:
        return

    LandingStatItem.objects.bulk_create([
        LandingStatItem(settings=settings, label='Kathmandu POS', value='Rs 18,400', dot_color='amber', group='primary', order=0),
        LandingStatItem(settings=settings, label='Online store', value='Order #1042', dot_color='green', group='primary', order=1),
        LandingStatItem(settings=settings, label='NCM dispatch', value='In transit', dot_color='blue', group='primary', order=2),
        LandingStatItem(settings=settings, label='Denim Jacket', value='47 in stock', dot_color='', group='secondary', order=0),
        LandingStatItem(settings=settings, label='Wool Sweater', value='28 in stock', dot_color='', group='secondary', order=1),
        LandingStatItem(settings=settings, label='Cotton Kurta', value='12 in stock', dot_color='', group='secondary', order=2),
    ])

    LandingBrandLogo.objects.bulk_create([
        LandingBrandLogo(settings=settings, name='Brand A', order=0),
        LandingBrandLogo(settings=settings, name='Brand B', order=1),
        LandingBrandLogo(settings=settings, name='Brand C', order=2),
        LandingBrandLogo(settings=settings, name='Brand D', order=3),
    ])

    platform_cards = [
        ('fas fa-box', 'Orders & dispatch', 'Full order lifecycle with follow-ups, returns, exchanges and return-to-vendor tracking.'),
        ('fas fa-boxes-stacked', 'Inventory & backorders', 'Atomic stock allocation, backorder queues, low-stock and expiry alerts.'),
        ('fas fa-truck-fast', 'Courier sync', 'NCM webhooks and Pick & Drop status sync keep every shipment up to date.'),
        ('fas fa-comments', 'AI customer CRM', 'Facebook and Instagram conversations routed, classified and answered with AI assistance.'),
        ('fas fa-receipt', 'Bill rewards', 'OCR reads uploaded receipts, matches them to orders and issues loyalty points.'),
        ('fas fa-user-clock', 'HR & payroll', 'Biometric attendance, leave, advances, payroll runs and payslips for your staff.'),
        ('fas fa-chart-line', 'Reports & forecasting', 'Sales reporting, staff performance and demand forecasting in one place.'),
        ('fas fa-user-shield', 'Role-based access', 'Granular per-user permissions across every module, so staff see only their work.'),
    ]
    LandingFeatureCard.objects.bulk_create([
        LandingFeatureCard(settings=settings, section='platform', icon=icon, title=title, description=desc, order=i)
        for i, (icon, title, desc) in enumerate(platform_cards)
    ])

    integration_cards = [
        ('fas fa-truck', 'Nepal Can Move', 'Courier & COD sync'),
        ('fas fa-dolly', 'Pick and Drop', 'Second courier network'),
        ('fab fa-facebook', 'Facebook & Instagram', 'Meta message sync'),
        ('fas fa-table', 'Google Sheets', 'Two-way order & product sync'),
        ('fas fa-fingerprint', 'ZKTeco devices', 'Biometric attendance'),
        ('fas fa-comment-sms', 'SMS gateways', 'Sparrow, Atuha, Twilio'),
    ]
    LandingFeatureCard.objects.bulk_create([
        LandingFeatureCard(settings=settings, section='integration', icon=icon, title=title, description=desc, order=i)
        for i, (icon, title, desc) in enumerate(integration_cards)
    ])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_add_landing_page_settings'),
    ]

    operations = [
        migrations.RunPython(seed_landing_defaults, noop_reverse),
    ]
