# Generated by Django 5.2 on 2026-08-13 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_apisettings_scheduler_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchitem',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='failure_code',
            field=models.CharField(blank=True, choices=[('already_dispatched', 'Already dispatched'), ('not_found', 'Order ID not found'), ('status_reverted', 'Status moved away from dispatched'), ('error', 'Processing error')], db_index=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=10)),
                ('event', models.CharField(choices=[('batch_created', 'Batch created'), ('order_dispatched', 'Order dispatched'), ('order_failed', 'Order failed'), ('order_not_found', 'Order not found'), ('stock_oversold', 'Stock oversold'), ('status_reverted', 'Status reverted'), ('batch_completed', 'Batch completed'), ('batch_error', 'Batch error')], db_index=True, default='batch_created', max_length=32)),
                ('message', models.TextField()),
                ('order_ref', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.dispatch')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='dashboard.dispatchitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispatch Log',
                'verbose_name_plural': 'Dispatch Logs',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['dispatch', 'created_at'], name='dashboard_d_dispatc_aa5de2_idx')],
            },
        ),
    ]
