# Generated by Django 5.2 on 2026-08-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_backfill_dispatch_failure_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manual_status_override_at',
            field=models.DateTimeField(blank=True, help_text="When staff last set this order's status by hand", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_status_override_ncm_status',
            field=models.CharField(blank=True, default='', help_text='Raw logistics status in force at the time of that manual change', max_length=100),
        ),
    ]
