# Generated by Django 5.2 on 2026-09-02 12:26

from django.db import migrations, models


def use_rupee_sign(apps, schema_editor):
    """0090 seeded the singleton before the default was corrected; the invoice
    has always printed रू, so move the placeholder over."""
    InvoiceTemplate = apps.get_model('dashboard', 'InvoiceTemplate')
    InvoiceTemplate.objects.filter(currency_symbol='NPR').update(currency_symbol='रू')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_seed_invoice_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetemplate',
            name='currency_symbol',
            field=models.CharField(default='रू', max_length=10),
        ),
        migrations.RunPython(use_rupee_sign, migrations.RunPython.noop),
    ]
