# Generated by Django 5.2 on 2026-09-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_alter_invoicetemplate_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_pan',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='VAT / PAN number'),
        ),
    ]
